import 'server-only';

import {
  createLocalDividendFromLegacyInput,
  deleteLocalDividendById,
  deleteUpcomingLocalAutoDividendsForAsset,
  getLocalDividendByIdAnyUser,
  hasLocalDuplicateDividend,
  listLocalDividends,
  listUpcomingLocalDividends,
  updateLocalDividendById,
} from '@/lib/server/dividends/localDividendService';
import {
  Dividend,
  DividendFormData,
  DividendStats,
  DividendsByAsset,
} from '@/types/dividend';
import { convertMultipleToEur, getExchangeRateToEur } from './currencyConversionService';

/**
 * Remove undefined fields from an object to prevent accidental null-writes.
 */
function removeUndefinedFields<T extends Record<string, any>>(obj: T): Partial<T> {
  const cleaned: Partial<T> = {};
  Object.keys(obj).forEach((key) => {
    const value = obj[key];
    if (value !== undefined) {
      cleaned[key as keyof T] = value;
    }
  });
  return cleaned;
}

/**
 * Get all dividends for a specific user
 * Sorted by payment date (most recent first)
 */
export async function getAllDividends(userId: string): Promise<Dividend[]> {
  try {
    return await listLocalDividends(userId);
  } catch (error) {
    console.error('[dividendService] Error getting dividends:', error);
    console.error('[dividendService] Error details:', {
      name: (error as Error).name,
      message: (error as Error).message,
      stack: (error as Error).stack,
    });
    throw error;
  }
}

/**
 * Get dividends for a specific asset
 * Sorted by payment date (most recent first)
 */
export async function getDividendsByAsset(
  userId: string,
  assetId: string
): Promise<Dividend[]> {
  try {
    return await listLocalDividends(userId, { assetId });
  } catch (error) {
    console.error('Error getting dividends by asset:', error);
    throw new Error('Failed to fetch dividends by asset');
  }
}

/**
 * Get dividends in a date range
 * Sorted by payment date (most recent first)
 */
export async function getDividendsByDateRange(
  userId: string,
  startDate: Date,
  endDate: Date
): Promise<Dividend[]> {
  try {
    return await listLocalDividends(userId, { startDate, endDate });
  } catch (error) {
    console.error('Error getting dividends by date range:', error);
    throw new Error('Failed to fetch dividends by date range');
  }
}

/**
 * Get a single dividend by ID
 */
export async function getDividendById(dividendId: string): Promise<Dividend | null> {
  try {
    return await getLocalDividendByIdAnyUser(dividendId);
  } catch (error) {
    console.error('Error getting dividend:', error);
    throw new Error('Failed to fetch dividend');
  }
}

/**
 * Compute a deterministic legacy ID for auto-generated dividends.
 * Format: {assetId}_{YYYY-MM-DD}_{dividendType}
 */
function buildDeterministicDividendId(assetId: string, exDate: Date, dividendType: string): string {
  const dateStr = exDate.toISOString().slice(0, 10); // "YYYY-MM-DD"
  return `${assetId}_${dateStr}_${dividendType}`;
}

/**
 * Create a new dividend
 */
export async function createDividend(
  userId: string,
  dividendData: DividendFormData,
  assetTicker: string,
  assetName: string,
  assetIsin?: string,
  isAutoGenerated: boolean = false
): Promise<string> {
  try {
    // Auto-calculate netAmount if not already set
    const netAmount = dividendData.netAmount || (dividendData.grossAmount - dividendData.taxAmount);

    // Convert dates to Date objects if they're strings
    const exDate = dividendData.exDate instanceof Date
      ? dividendData.exDate
      : new Date(dividendData.exDate);
    const paymentDate = dividendData.paymentDate instanceof Date
      ? dividendData.paymentDate
      : new Date(dividendData.paymentDate);

    // Currency conversion to EUR
    let grossAmountEur: number | undefined;
    let taxAmountEur: number | undefined;
    let netAmountEur: number | undefined;
    let exchangeRate: number | undefined;

    if (dividendData.currency.toUpperCase() !== 'EUR') {
      try {
        exchangeRate = await getExchangeRateToEur(dividendData.currency);

        const [convertedGross, convertedTax, convertedNet] = await convertMultipleToEur(
          [dividendData.grossAmount, dividendData.taxAmount, netAmount],
          dividendData.currency
        );

        grossAmountEur = convertedGross;
        taxAmountEur = convertedTax;
        netAmountEur = convertedNet;

        console.log(`[dividendService] Converted dividend from ${dividendData.currency} to EUR using rate ${exchangeRate}`);
      } catch (conversionError) {
        console.error('[dividendService] Currency conversion failed:', conversionError);
      }
    }

    const createdDividend = await createLocalDividendFromLegacyInput(userId, {
      dividendData: {
        ...dividendData,
        exDate,
        paymentDate,
        netAmount,
        isAutoGenerated,
      },
      assetTicker,
      assetName,
      assetIsin,
      isAutoGenerated,
      grossAmountEur,
      taxAmountEur,
      netAmountEur,
      exchangeRate,
      legacyDeterministicId: isAutoGenerated
        ? buildDeterministicDividendId(dividendData.assetId, exDate, dividendData.dividendType)
        : undefined,
    });

    return createdDividend.id;
  } catch (error) {
    console.error('Error creating dividend:', error);
    throw new Error('Failed to create dividend');
  }
}

/**
 * Update an existing dividend
 * Recalculates EUR amounts if currency or amounts are changed
 */
export async function updateDividend(
  dividendId: string,
  updates: Partial<DividendFormData>
): Promise<void> {
  try {
    // Convert dates to Date objects if they're strings
    const exDate = updates.exDate
      ? (updates.exDate instanceof Date ? updates.exDate : new Date(updates.exDate))
      : undefined;
    const paymentDate = updates.paymentDate
      ? (updates.paymentDate instanceof Date ? updates.paymentDate : new Date(updates.paymentDate))
      : undefined;

    // Recalculate netAmount if gross or tax amounts changed
    let netAmount = updates.netAmount;
    if (updates.grossAmount !== undefined && updates.taxAmount !== undefined && !netAmount) {
      netAmount = updates.grossAmount - updates.taxAmount;
    }

    // Currency conversion to EUR (if currency is provided in updates)
    let grossAmountEur: number | undefined;
    let taxAmountEur: number | undefined;
    let netAmountEur: number | undefined;
    let exchangeRate: number | undefined;

    if (updates.currency && updates.currency.toUpperCase() !== 'EUR') {
      try {
        exchangeRate = await getExchangeRateToEur(updates.currency);

        const amountsToConvert: number[] = [];
        if (updates.grossAmount !== undefined) amountsToConvert.push(updates.grossAmount);
        if (updates.taxAmount !== undefined) amountsToConvert.push(updates.taxAmount);
        if (netAmount !== undefined) amountsToConvert.push(netAmount);

        if (amountsToConvert.length > 0) {
          const convertedAmounts = await convertMultipleToEur(amountsToConvert, updates.currency);

          if (updates.grossAmount !== undefined) grossAmountEur = convertedAmounts.shift();
          if (updates.taxAmount !== undefined) taxAmountEur = convertedAmounts.shift();
          if (netAmount !== undefined) netAmountEur = convertedAmounts.shift();

          console.log(`[dividendService] Updated dividend with EUR conversion using rate ${exchangeRate}`);
        }
      } catch (conversionError) {
        console.error('[dividendService] Currency conversion failed during update:', conversionError);
      }
    } else if (updates.currency && updates.currency.toUpperCase() === 'EUR') {
      grossAmountEur = undefined;
      taxAmountEur = undefined;
      netAmountEur = undefined;
      exchangeRate = undefined;
    }

    const cleanedUpdates = removeUndefinedFields({
      ...updates,
      netAmount,
      exDate,
      paymentDate,
      grossAmountEur,
      taxAmountEur,
      netAmountEur,
      exchangeRate,
      updatedAt: new Date(),
    });

    await updateLocalDividendById(dividendId, cleanedUpdates as any);
  } catch (error) {
    console.error('Error updating dividend:', error);
    throw new Error('Failed to update dividend');
  }
}

/**
 * Delete a dividend
 */
export async function deleteDividend(dividendId: string): Promise<void> {
  try {
    await deleteLocalDividendById(dividendId);
  } catch (error) {
    console.error('Error deleting dividend:', error);
    throw new Error('Failed to delete dividend');
  }
}

/**
 * Calculate dividend statistics for a user
 */
export async function calculateDividendStats(
  userId: string,
  startDate?: Date,
  endDate?: Date,
  assetId?: string
): Promise<DividendStats> {
  try {
    let dividends: Dividend[];

    if (startDate && endDate) {
      dividends = await getDividendsByDateRange(userId, startDate, endDate);
    } else {
      dividends = await getAllDividends(userId);
    }

    if (assetId) {
      dividends = dividends.filter(d => d.assetId === assetId);
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const paidDividends = dividends.filter(div => {
      const paymentDate = div.paymentDate instanceof Date ? div.paymentDate : new Date();
      return paymentDate <= today;
    });

    const stats: DividendStats = {
      totalGross: 0,
      totalTax: 0,
      totalNet: 0,
      count: paidDividends.length,
      byAsset: {},
      byType: {
        ordinary: { totalGross: 0, totalTax: 0, totalNet: 0, count: 0 },
        extraordinary: { totalGross: 0, totalTax: 0, totalNet: 0, count: 0 },
        interim: { totalGross: 0, totalTax: 0, totalNet: 0, count: 0 },
        final: { totalGross: 0, totalTax: 0, totalNet: 0, count: 0 },
        coupon: { totalGross: 0, totalTax: 0, totalNet: 0, count: 0 },
        finalPremium: { totalGross: 0, totalTax: 0, totalNet: 0, count: 0 },
      },
    };

    paidDividends.forEach(dividend => {
      stats.totalGross += dividend.grossAmount;
      stats.totalTax += dividend.taxAmount;
      stats.totalNet += dividend.netAmount;

      if (!stats.byAsset[dividend.assetId]) {
        stats.byAsset[dividend.assetId] = {
          assetTicker: dividend.assetTicker,
          assetName: dividend.assetName,
          totalGross: 0,
          totalTax: 0,
          totalNet: 0,
          count: 0,
        };
      }
      stats.byAsset[dividend.assetId].totalGross += dividend.grossAmount;
      stats.byAsset[dividend.assetId].totalTax += dividend.taxAmount;
      stats.byAsset[dividend.assetId].totalNet += dividend.netAmount;
      stats.byAsset[dividend.assetId].count += 1;

      stats.byType[dividend.dividendType].totalGross += dividend.grossAmount;
      stats.byType[dividend.dividendType].totalTax += dividend.taxAmount;
      stats.byType[dividend.dividendType].totalNet += dividend.netAmount;
      stats.byType[dividend.dividendType].count += 1;
    });

    return stats;
  } catch (error) {
    console.error('Error calculating dividend stats:', error);
    throw new Error('Failed to calculate dividend stats');
  }
}

/**
 * Get dividends grouped by asset
 * Returns array of assets with their dividends and totals
 */
export async function getDividendsByAssetGrouped(
  userId: string
): Promise<DividendsByAsset[]> {
  try {
    const dividends = await getAllDividends(userId);

    const groupedMap = new Map<string, DividendsByAsset>();

    dividends.forEach(dividend => {
      if (!groupedMap.has(dividend.assetId)) {
        groupedMap.set(dividend.assetId, {
          assetId: dividend.assetId,
          assetTicker: dividend.assetTicker,
          assetName: dividend.assetName,
          dividends: [],
          totalGross: 0,
          totalTax: 0,
          totalNet: 0,
        });
      }

      const group = groupedMap.get(dividend.assetId)!;
      group.dividends.push(dividend);
      group.totalGross += dividend.grossAmount;
      group.totalTax += dividend.taxAmount;
      group.totalNet += dividend.netAmount;
    });

    return Array.from(groupedMap.values()).sort(
      (a, b) => b.totalNet - a.totalNet
    );
  } catch (error) {
    console.error('Error getting dividends grouped by asset:', error);
    throw new Error('Failed to get dividends grouped by asset');
  }
}

/**
 * Get upcoming dividends (payment date in the future)
 * Sorted by payment date (nearest first)
 */
export async function getUpcomingDividends(userId: string): Promise<Dividend[]> {
  try {
    return await listUpcomingLocalDividends(userId, new Date());
  } catch (error) {
    console.error('Error getting upcoming dividends:', error);
    throw new Error('Failed to fetch upcoming dividends');
  }
}

/**
 * Check if a dividend already exists for an asset on a specific ex-date
 */
export async function isDuplicateDividend(
  userId: string,
  assetId: string,
  exDate: Date
): Promise<boolean> {
  try {
    const startOfDay = new Date(exDate);
    startOfDay.setHours(0, 0, 0, 0);
    const endOfDay = new Date(exDate);
    endOfDay.setHours(23, 59, 59, 999);

    return await hasLocalDuplicateDividend(userId, assetId, startOfDay, endOfDay);
  } catch (error) {
    console.error('Error checking duplicate dividend:', error);
    throw new Error('Failed to check duplicate dividend');
  }
}

/**
 * Calculate withholding tax amount
 * Default Italian withholding tax rate: 26%
 */
export function calculateWithholdingTax(
  grossAmount: number,
  taxRate: number = 26
): number {
  return grossAmount * (taxRate / 100);
}

/**
 * Delete all upcoming auto-generated coupon dividends for an asset.
 */
export async function deleteUpcomingCouponsForAsset(
  userId: string,
  assetId: string
): Promise<void> {
  const now = new Date();
  now.setHours(0, 0, 0, 0);

  await deleteUpcomingLocalAutoDividendsForAsset(userId, assetId, 'coupon', now);
}

/**
 * Deletes all auto-generated finalPremium dividends for an asset.
 */
export async function deleteUpcomingFinalPremiumForAsset(
  userId: string,
  assetId: string
): Promise<void> {
  await deleteUpcomingLocalAutoDividendsForAsset(userId, assetId, 'finalPremium');
}
