import "server-only";

import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/server/prisma";
import type { Dividend, DividendFormData } from "@/types/dividend";

export type LocalDividendListFilters = {
  assetId?: string;
  startDate?: Date;
  endDate?: Date;
};

export type LocalDividendCreateLegacyInput = {
  dividendData: DividendFormData;
  assetTicker?: string;
  assetName?: string;
  assetIsin?: string;
  isAutoGenerated?: boolean;
  grossAmountEur?: number;
  taxAmountEur?: number;
  netAmountEur?: number;
  exchangeRate?: number;
  legacyDeterministicId?: string;
};

export type LocalDividendUpdateInput = Partial<DividendFormData> & {
  expenseId?: string;
  grossAmountEur?: number;
  taxAmountEur?: number;
  netAmountEur?: number;
  exchangeRate?: number;
  updatedAt?: Date;
};

type AssetRow = {
  id: string;
  ticker: string;
  name: string;
  metadata: Prisma.JsonValue;
};

type DividendRow = {
  id: string;
  userId: string;
  assetId: string;
  assetTicker: string;
  assetName: string;
  assetIsin: string | null;
  exDate: Date;
  paymentDate: Date;
  dividendPerShare: number;
  quantity: number;
  grossAmount: number;
  taxAmount: number;
  netAmount: number;
  currency: string;
  dividendType: string;
  notes: string | null;
  isAutoGenerated: boolean;
  expenseId: string | null;
  grossAmountEur: number | null;
  taxAmountEur: number | null;
  netAmountEur: number | null;
  exchangeRate: number | null;
  costPerShare: number | null;
  createdAt: Date;
  updatedAt: Date;
};

export async function listLocalDividends(
  userId: string,
  filters: LocalDividendListFilters = {}
): Promise<Dividend[]> {
  const rows = await prisma.dividend.findMany({
    where: buildDividendWhere(userId, filters),
    orderBy: [{ paymentDate: "desc" }, { createdAt: "desc" }],
  });

  return rows.map(mapDividendRow);
}

export async function getLocalDividendById(
  userId: string,
  dividendId: string
): Promise<Dividend | null> {
  const row = await prisma.dividend.findFirst({
    where: { id: dividendId, userId },
  });

  return row ? mapDividendRow(row) : null;
}

export async function getLocalDividendByIdAnyUser(
  dividendId: string
): Promise<Dividend | null> {
  const row = await prisma.dividend.findUnique({
    where: { id: dividendId },
  });

  return row ? mapDividendRow(row) : null;
}

export async function createLocalDividend(
  userId: string,
  dividendData: DividendFormData
): Promise<Dividend> {
  const asset = await prisma.asset.findUnique({
    where: { id_userId: { id: dividendData.assetId, userId } },
  });

  if (!asset) {
    throw new Error("Asset not found");
  }

  const row = await prisma.dividend.create({
    data: {
      userId,
      ...buildDividendData(dividendData, asset),
    },
  });

  return mapDividendRow(row);
}

export async function createLocalDividendFromLegacyInput(
  userId: string,
  input: LocalDividendCreateLegacyInput
): Promise<Dividend> {
  const asset = await prisma.asset.findUnique({
    where: { id_userId: { id: input.dividendData.assetId, userId } },
  });

  const assetMetadata = getAssetMetadata(asset);
  const assetTicker = input.assetTicker ?? asset?.ticker;
  const assetName = input.assetName ?? asset?.name;
  const assetIsin = input.assetIsin ?? getAssetIsin(assetMetadata);

  if (!assetTicker || !assetName) {
    throw new Error("Asset not found");
  }

  const data = buildDividendData(input.dividendData, asset, {
    assetTicker,
    assetName,
    assetIsin,
    isAutoGenerated: input.isAutoGenerated,
    grossAmountEur: input.grossAmountEur,
    taxAmountEur: input.taxAmountEur,
    netAmountEur: input.netAmountEur,
    exchangeRate: input.exchangeRate,
    legacyFirebaseId: input.legacyDeterministicId,
  });

  if (input.isAutoGenerated && input.legacyDeterministicId) {
    const row = await prisma.dividend.upsert({
      where: {
        userId_legacyFirebaseId: {
          userId,
          legacyFirebaseId: input.legacyDeterministicId,
        },
      },
      update: {
        ...data,
        updatedAt: new Date(),
      },
      create: {
        userId,
        ...data,
      },
    });

    return mapDividendRow(row);
  }

  const row = await prisma.dividend.create({
    data: {
      userId,
      ...data,
    },
  });

  return mapDividendRow(row);
}

export async function updateLocalDividend(
  userId: string,
  dividendId: string,
  updates: LocalDividendUpdateInput
): Promise<Dividend | null> {
  try {
    const asset = updates.assetId
      ? await prisma.asset.findUnique({
          where: { id_userId: { id: updates.assetId, userId } },
        })
      : undefined;

    if (updates.assetId && !asset) {
      throw new Error("Asset not found");
    }

    const row = await prisma.dividend.update({
      where: { id_userId: { id: dividendId, userId } },
      data: buildDividendUpdateData(updates, asset),
    });

    return mapDividendRow(row);
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") {
      return null;
    }

    throw error;
  }
}

export async function updateLocalDividendById(
  dividendId: string,
  updates: LocalDividendUpdateInput
): Promise<Dividend | null> {
  try {
    const asset = updates.assetId
      ? await prisma.asset.findUnique({
          where: { id: updates.assetId },
        })
      : undefined;

    if (updates.assetId && !asset) {
      throw new Error("Asset not found");
    }

    const row = await prisma.dividend.update({
      where: { id: dividendId },
      data: buildDividendUpdateData(updates, asset),
    });

    return mapDividendRow(row);
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") {
      return null;
    }

    throw error;
  }
}

export async function deleteLocalDividend(
  userId: string,
  dividendId: string
): Promise<boolean> {
  const result = await prisma.dividend.deleteMany({
    where: { id: dividendId, userId },
  });

  return result.count > 0;
}

export async function deleteLocalDividendById(dividendId: string): Promise<boolean> {
  const result = await prisma.dividend.deleteMany({
    where: { id: dividendId },
  });

  return result.count > 0;
}

export async function listUpcomingLocalDividends(
  userId: string,
  fromDate: Date
): Promise<Dividend[]> {
  const rows = await prisma.dividend.findMany({
    where: {
      userId,
      paymentDate: {
        gte: fromDate,
      },
    },
    orderBy: [{ paymentDate: "asc" }, { createdAt: "asc" }],
  });

  return rows.map(mapDividendRow);
}

export async function hasLocalDuplicateDividend(
  userId: string,
  assetId: string,
  startDate: Date,
  endDate: Date
): Promise<boolean> {
  const row = await prisma.dividend.findFirst({
    where: {
      userId,
      assetId,
      exDate: {
        gte: startDate,
        lte: endDate,
      },
    },
  });

  return Boolean(row);
}

export async function deleteUpcomingLocalAutoDividendsForAsset(
  userId: string,
  assetId: string,
  dividendType: Dividend["dividendType"],
  fromDate?: Date
): Promise<number> {
  const result = await prisma.dividend.deleteMany({
    where: {
      userId,
      assetId,
      dividendType,
      isAutoGenerated: true,
      ...(fromDate
        ? {
            paymentDate: {
              gte: fromDate,
            },
          }
        : {}),
    },
  });

  return result.count;
}

function buildDividendWhere(
  userId: string,
  filters: LocalDividendListFilters
): Prisma.DividendWhereInput {
  const where: Prisma.DividendWhereInput = { userId };

  if (filters.assetId) {
    where.assetId = filters.assetId;
  }

  if (filters.startDate || filters.endDate) {
    where.paymentDate = {
      gte: filters.startDate,
      lte: filters.endDate,
    };
  }

  return where;
}

function buildDividendData(
  dividendData: DividendFormData,
  asset?: AssetRow | null,
  overrides: {
    assetTicker?: string;
    assetName?: string;
    assetIsin?: string;
    isAutoGenerated?: boolean;
    grossAmountEur?: number;
    taxAmountEur?: number;
    netAmountEur?: number;
    exchangeRate?: number;
    legacyFirebaseId?: string;
  } = {}
): Omit<Prisma.DividendUncheckedCreateInput, "userId"> {
  const metadata = getAssetMetadata(asset);
  const assetTicker = overrides.assetTicker ?? asset?.ticker;
  const assetName = overrides.assetName ?? asset?.name;

  return {
    assetId: dividendData.assetId,
    assetTicker: assetTicker ?? "",
    assetName: assetName ?? "",
    assetIsin: overrides.assetIsin ?? getAssetIsin(metadata),
    exDate: dividendData.exDate,
    paymentDate: dividendData.paymentDate,
    dividendPerShare: dividendData.dividendPerShare,
    quantity: dividendData.quantity,
    grossAmount: dividendData.grossAmount,
    taxAmount: dividendData.taxAmount,
    netAmount: dividendData.netAmount || (dividendData.grossAmount - dividendData.taxAmount),
    currency: dividendData.currency,
    dividendType: dividendData.dividendType,
    notes: dividendData.notes,
    isAutoGenerated: overrides.isAutoGenerated ?? dividendData.isAutoGenerated,
    grossAmountEur: overrides.grossAmountEur,
    taxAmountEur: overrides.taxAmountEur,
    netAmountEur: overrides.netAmountEur,
    exchangeRate: overrides.exchangeRate,
    costPerShare: dividendData.costPerShare ?? getAverageCost(metadata),
    legacyFirebaseId: overrides.legacyFirebaseId,
  };
}

function buildDividendUpdateData(
  updates: LocalDividendUpdateInput,
  asset?: AssetRow | null
): Prisma.DividendUncheckedUpdateInput {
  const netAmount = updates.netAmount ?? (
    updates.grossAmount !== undefined && updates.taxAmount !== undefined
      ? updates.grossAmount - updates.taxAmount
      : undefined
  );
  const metadata = getAssetMetadata(asset);

  return stripUndefined({
    assetId: updates.assetId,
    assetTicker: asset?.ticker,
    assetName: asset?.name,
    assetIsin: getAssetIsin(metadata),
    exDate: updates.exDate,
    paymentDate: updates.paymentDate,
    dividendPerShare: updates.dividendPerShare,
    quantity: updates.quantity,
    grossAmount: updates.grossAmount,
    taxAmount: updates.taxAmount,
    netAmount,
    currency: updates.currency,
    dividendType: updates.dividendType,
    notes: updates.notes,
    isAutoGenerated: updates.isAutoGenerated,
    expenseId: updates.expenseId,
    grossAmountEur: updates.grossAmountEur,
    taxAmountEur: updates.taxAmountEur,
    netAmountEur: updates.netAmountEur,
    exchangeRate: updates.exchangeRate,
    costPerShare: updates.costPerShare ?? getAverageCost(metadata),
    updatedAt: updates.updatedAt,
  });
}

function mapDividendRow(row: DividendRow): Dividend {
  return {
    id: row.id,
    userId: row.userId,
    assetId: row.assetId,
    assetTicker: row.assetTicker,
    assetName: row.assetName,
    assetIsin: row.assetIsin ?? undefined,
    exDate: row.exDate,
    paymentDate: row.paymentDate,
    dividendPerShare: row.dividendPerShare,
    quantity: row.quantity,
    grossAmount: row.grossAmount,
    taxAmount: row.taxAmount,
    netAmount: row.netAmount,
    currency: row.currency,
    dividendType: row.dividendType as Dividend["dividendType"],
    notes: row.notes ?? undefined,
    isAutoGenerated: row.isAutoGenerated,
    expenseId: row.expenseId ?? undefined,
    grossAmountEur: row.grossAmountEur ?? undefined,
    taxAmountEur: row.taxAmountEur ?? undefined,
    netAmountEur: row.netAmountEur ?? undefined,
    exchangeRate: row.exchangeRate ?? undefined,
    costPerShare: row.costPerShare ?? undefined,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function getAverageCost(metadata: Record<string, unknown>): number | undefined {
  return typeof metadata.averageCost === "number" ? metadata.averageCost : undefined;
}

function getAssetIsin(metadata: Record<string, unknown>): string | undefined {
  return typeof metadata.isin === "string" ? metadata.isin : undefined;
}

function getAssetMetadata(asset?: AssetRow | null): Record<string, unknown> {
  return asset && isRecord(asset.metadata) ? asset.metadata : {};
}

function isRecord(input: unknown): input is Record<string, unknown> {
  return typeof input === "object" && input !== null && !Array.isArray(input);
}

function stripUndefined<T extends Record<string, unknown>>(input: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(input).filter(([, value]) => value !== undefined)
  ) as Partial<T>;
}
