import "server-only";

import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/server/prisma";
import { scrapeLocalAssetDividends } from "@/lib/server/dividends/localDividendScrapeService";
import { syncLocalDividendExpenses } from "@/lib/server/dividends/localDividendExpenseSyncService";
import {
  calculateCouponPerShare,
  getApplicableCouponRate,
  getFollowingCouponDate,
} from "@/lib/utils/couponUtils";
import type { BondDetails, CouponFrequency, CouponRateTier } from "@/types/assets";

export type LocalDailyDividendProcessingOptions = {
  today?: Date;
};

export type LocalDailyDividendProcessingResult = {
  success: true;
  message: string;
  timestamp: string;
  scraping: {
    assetsScraped: number;
    newDividends: number;
    errors: number;
  };
  expenseCreation: {
    processedCount: number;
    errorCount: number;
    processedDividends: Array<{
      userId: string;
      dividendId: string;
      expenseId: string;
      amount: number;
      asset: string;
    }>;
    errors: Array<{ userId: string; dividendId?: string; error: string }>;
  };
  couponScheduling: {
    scheduled: number;
    skipped: number;
    errors: number;
  };
};

type UserRow = { id: string };
type AssetLookupRow = { id: string; metadata: Prisma.JsonValue };
type CouponDividendRow = Awaited<ReturnType<typeof prisma.dividend.findMany>>[number];
type AssetRow = Awaited<ReturnType<typeof prisma.asset.findUnique>>;

export async function runLocalDailyDividendProcessing(
  options: LocalDailyDividendProcessingOptions = {}
): Promise<LocalDailyDividendProcessingResult> {
  const today = startOfDay(options.today ?? new Date());
  const users = await prisma.user.findMany({ select: { id: true } });
  const scraping = await runLocalDividendScraping(users, today);
  const expenseCreation = await runLocalExpenseCreation(users, today);
  const couponScheduling = await runLocalCouponScheduling(users, today);

  return {
    success: true,
    message: "Daily dividend processing job completed",
    timestamp: new Date().toISOString(),
    scraping,
    expenseCreation,
    couponScheduling,
  };
}

async function runLocalDividendScraping(users: UserRow[], today: Date) {
  const result = {
    assetsScraped: 0,
    newDividends: 0,
    errors: 0,
  };

  for (const user of users) {
    const assets = await prisma.asset.findMany({
      where: { userId: user.id, assetClass: "equity" },
      select: { id: true, metadata: true },
    });

    for (const asset of assets.filter(hasIsin)) {
      try {
        const scrapeResult = await scrapeLocalAssetDividends(user.id, asset.id, { today });
        result.assetsScraped += 1;
        result.newDividends += scrapeResult.created;
      } catch (error) {
        console.error("[LOCAL_DAILY_DIVIDEND_SCRAPE_ERROR]", error);
        result.errors += 1;
      }
    }
  }

  return result;
}

async function runLocalExpenseCreation(users: UserRow[], today: Date) {
  const result: LocalDailyDividendProcessingResult["expenseCreation"] = {
    processedCount: 0,
    errorCount: 0,
    processedDividends: [],
    errors: [],
  };

  for (const user of users) {
    try {
      const categoryInfo = await getDividendIncomeCategoryInfo(user.id);
      if (!categoryInfo) {
        continue;
      }

      const syncResult = await syncLocalDividendExpenses(user.id, {
        ...categoryInfo,
        today,
      });
      result.processedCount += syncResult.created;
      result.errorCount += syncResult.failed;
    } catch (error) {
      result.errorCount += 1;
      result.errors.push({ userId: user.id, error: (error as Error).message });
    }
  }

  return result;
}

async function runLocalCouponScheduling(users: UserRow[], today: Date) {
  const result = {
    scheduled: 0,
    skipped: 0,
    errors: 0,
  };
  const todayEnd = endOfDay(today);

  for (const user of users) {
    const coupons = await prisma.dividend.findMany({
      where: {
        userId: user.id,
        dividendType: "coupon",
        isAutoGenerated: true,
        paymentDate: {
          gte: today,
          lte: todayEnd,
        },
      },
    });

    for (const coupon of coupons) {
      try {
        const scheduled = await scheduleNextCoupon(user.id, coupon);
        if (scheduled) {
          result.scheduled += 1;
        } else {
          result.skipped += 1;
        }
      } catch (error) {
        console.error("[LOCAL_DAILY_COUPON_SCHEDULING_ERROR]", error);
        result.errors += 1;
      }
    }
  }

  return result;
}

async function scheduleNextCoupon(
  userId: string,
  coupon: CouponDividendRow
): Promise<boolean> {
  const asset = await prisma.asset.findUnique({
    where: { id_userId: { id: coupon.assetId, userId } },
  });

  if (!asset) {
    return false;
  }

  const assetMetadata = isRecord(asset.metadata) ? asset.metadata : {};
  const bondDetails = parseBondDetails(assetMetadata.bondDetails);
  if (!bondDetails) {
    return false;
  }

  const nextDate = getFollowingCouponDate(
    coupon.paymentDate,
    bondDetails.couponFrequency,
    bondDetails.maturityDate
  );
  if (!nextDate) {
    return false;
  }

  const duplicate = await prisma.dividend.findFirst({
    where: {
      userId,
      assetId: coupon.assetId,
      exDate: {
        gte: startOfDay(nextDate),
        lte: endOfDay(nextDate),
      },
    },
  });
  if (duplicate) {
    return false;
  }

  const taxRate = typeof assetMetadata.taxRate === "number" && assetMetadata.taxRate > 0
    ? assetMetadata.taxRate
    : 26;
  const nominalValue = bondDetails.nominalValue ?? 1;
  const effectiveRate = getApplicableCouponRate(
    nextDate,
    bondDetails.issueDate,
    bondDetails.couponRate,
    bondDetails.couponRateSchedule
  );
  const dividendPerShare = calculateCouponPerShare(
    effectiveRate,
    nominalValue,
    bondDetails.couponFrequency
  );
  const grossAmount = dividendPerShare * asset.quantity;
  const taxAmount = grossAmount * (taxRate / 100);

  await prisma.dividend.create({
    data: {
      userId,
      assetId: coupon.assetId,
      assetTicker: coupon.assetTicker,
      assetName: coupon.assetName,
      assetIsin: typeof assetMetadata.isin === "string" ? assetMetadata.isin : undefined,
      exDate: nextDate,
      paymentDate: nextDate,
      dividendPerShare,
      quantity: asset.quantity,
      grossAmount,
      taxAmount,
      netAmount: grossAmount - taxAmount,
      currency: coupon.currency,
      dividendType: "coupon",
      notes: `Cedola ${bondDetails.couponFrequency} - tasso annuo ${bondDetails.couponRate}%`,
      isAutoGenerated: true,
      costPerShare: typeof assetMetadata.averageCost === "number"
        ? assetMetadata.averageCost
        : undefined,
    },
  });

  return true;
}

async function getDividendIncomeCategoryInfo(userId: string) {
  const settings = await prisma.userSetting.findUnique({ where: { userId } });
  const settingsData = settings?.data && isRecord(settings.data) ? settings.data : {};
  const categoryId = typeof settingsData.dividendIncomeCategoryId === "string"
    ? settingsData.dividendIncomeCategoryId
    : undefined;

  if (!categoryId) {
    return null;
  }

  const category = await prisma.expenseCategory.findUnique({
    where: { id_userId: { id: categoryId, userId } },
  });

  if (!category) {
    return null;
  }

  const subCategoryId = typeof settingsData.dividendIncomeSubCategoryId === "string"
    ? settingsData.dividendIncomeSubCategoryId
    : undefined;
  const subCategories = Array.isArray(category.subCategories)
    ? (category.subCategories as Array<{ id: string; name: string }>)
    : [];
  const subCategory = subCategoryId
    ? subCategories.find((candidate) => candidate.id === subCategoryId)
    : undefined;

  return {
    categoryId,
    categoryName: category.name,
    subCategoryId,
    subCategoryName: subCategory?.name,
  };
}

function hasIsin(asset: AssetLookupRow) {
  const metadata = isRecord(asset.metadata) ? asset.metadata : {};
  return typeof metadata.isin === "string" && metadata.isin.trim().length > 0;
}

function parseBondDetails(input: unknown): (Omit<BondDetails, "issueDate" | "maturityDate"> & {
  issueDate: Date;
  maturityDate: Date;
  couponFrequency: CouponFrequency;
  couponRateSchedule?: CouponRateTier[];
}) | null {
  if (!isRecord(input)) {
    return null;
  }

  const issueDate = toDate(input.issueDate);
  const maturityDate = toDate(input.maturityDate);
  const couponRate = typeof input.couponRate === "number" ? input.couponRate : undefined;
  const couponFrequency = input.couponFrequency;

  if (
    !issueDate ||
    !maturityDate ||
    couponRate === undefined ||
    !isCouponFrequency(couponFrequency)
  ) {
    return null;
  }

  return {
    issueDate,
    maturityDate,
    couponRate,
    couponFrequency,
    nominalValue: typeof input.nominalValue === "number" ? input.nominalValue : undefined,
    couponRateSchedule: Array.isArray(input.couponRateSchedule)
      ? (input.couponRateSchedule as CouponRateTier[])
      : undefined,
  };
}

function isCouponFrequency(input: unknown): input is CouponFrequency {
  return ["monthly", "quarterly", "semiannual", "annual"].includes(String(input));
}

function toDate(input: unknown): Date | null {
  if (input instanceof Date) {
    return input;
  }

  if (typeof input === "string") {
    const date = new Date(input);
    return Number.isNaN(date.getTime()) ? null : date;
  }

  return null;
}

function startOfDay(date: Date) {
  const result = new Date(date);
  result.setUTCHours(0, 0, 0, 0);
  return result;
}

function endOfDay(date: Date) {
  const result = new Date(date);
  result.setUTCHours(23, 59, 59, 999);
  return result;
}

function isRecord(input: unknown): input is Record<string, unknown> {
  return typeof input === "object" && input !== null && !Array.isArray(input);
}
