import "server-only";

import { Prisma } from "@prisma/client";
import { scrapeDividendsByIsin } from "@/lib/services/borsaItalianaScraperService";
import { prisma } from "@/lib/server/prisma";
import { syncLocalDividendExpenses } from "@/lib/server/dividends/localDividendExpenseSyncService";
import type { AssetType } from "@/types/assets";
import type { DividendType, ScrapedDividend } from "@/types/dividend";

export type LocalDividendScrapeOptions = {
  today?: Date;
};

export type LocalDividendScrapeResult = {
  success: true;
  message: string;
  scraped: number;
  filtered: number;
  created: number;
  skipped: number;
  createdIds: string[];
};

type LocalAssetForScrape = {
  id: string;
  ticker: string;
  name: string;
  type: AssetType;
  quantity: number;
  metadata: Prisma.JsonValue;
  createdAt: Date;
};

type DividendIncomeCategoryInfo = {
  categoryId: string;
  categoryName: string;
  subCategoryId?: string;
  subCategoryName?: string;
};

export async function scrapeLocalAssetDividends(
  userId: string,
  assetId: string,
  options: LocalDividendScrapeOptions = {}
): Promise<LocalDividendScrapeResult> {
  const asset = await prisma.asset.findUnique({
    where: { id_userId: { id: assetId, userId } },
  });

  if (!asset) {
    throw new Error("ASSET_NOT_FOUND");
  }

  const localAsset = mapAssetForScrape(asset);
  const metadata = isRecord(localAsset.metadata) ? localAsset.metadata : {};
  const isin = typeof metadata.isin === "string" ? metadata.isin : undefined;
  const averageCost = typeof metadata.averageCost === "number"
    ? metadata.averageCost
    : undefined;

  if (!isin) {
    throw new Error("ASSET_MISSING_ISIN");
  }

  const scrapedDividends = await scrapeDividendsByIsin(isin, localAsset.type);
  const relevantDividends = scrapedDividends.filter(
    (dividend) => dividend.exDate >= localAsset.createdAt
  );
  const categoryInfo = await getDividendIncomeCategoryInfo(userId);
  const createdIds: string[] = [];
  let skipped = 0;

  for (const scrapedDividend of relevantDividends) {
    const duplicate = await hasDividendOnExDate(userId, assetId, scrapedDividend.exDate);
    if (duplicate) {
      skipped += 1;
      continue;
    }

    const createdDividend = await createScrapedDividend({
      userId,
      assetId,
      asset: localAsset,
      isin,
      averageCost,
      scrapedDividend,
    });
    createdIds.push(createdDividend.id);
  }

  if (categoryInfo && createdIds.length > 0) {
    await syncLocalDividendExpenses(userId, {
      dividendIds: createdIds,
      ...categoryInfo,
      today: options.today,
    });
  }

  return {
    success: true,
    message: `Dividendi importati per ${localAsset.ticker}`,
    scraped: scrapedDividends.length,
    filtered: scrapedDividends.length - relevantDividends.length,
    created: createdIds.length,
    skipped,
    createdIds,
  };
}

async function hasDividendOnExDate(
  userId: string,
  assetId: string,
  exDate: Date
): Promise<boolean> {
  const startOfDay = new Date(exDate);
  startOfDay.setHours(0, 0, 0, 0);
  const endOfDay = new Date(exDate);
  endOfDay.setHours(23, 59, 59, 999);

  const existing = await prisma.dividend.findFirst({
    where: {
      userId,
      assetId,
      exDate: {
        gte: startOfDay,
        lte: endOfDay,
      },
    },
  });

  return Boolean(existing);
}

async function createScrapedDividend(input: {
  userId: string;
  assetId: string;
  asset: LocalAssetForScrape;
  isin: string;
  averageCost?: number;
  scrapedDividend: ScrapedDividend;
}) {
  const grossAmount = input.scrapedDividend.dividendPerShare * input.asset.quantity;
  const taxAmount = grossAmount * 0.26;
  const netAmount = grossAmount - taxAmount;

  return prisma.dividend.create({
    data: {
      userId: input.userId,
      assetId: input.assetId,
      assetTicker: input.asset.ticker,
      assetName: input.asset.name,
      assetIsin: input.isin,
      exDate: input.scrapedDividend.exDate,
      paymentDate: input.scrapedDividend.paymentDate,
      dividendPerShare: input.scrapedDividend.dividendPerShare,
      quantity: input.asset.quantity,
      grossAmount,
      taxAmount,
      netAmount,
      currency: input.scrapedDividend.currency,
      dividendType: input.scrapedDividend.dividendType as DividendType,
      isAutoGenerated: true,
      costPerShare: input.averageCost,
    },
  });
}

async function getDividendIncomeCategoryInfo(
  userId: string
): Promise<DividendIncomeCategoryInfo | null> {
  const settings = await prisma.userSetting.findUnique({ where: { userId } });
  const settingsData = settings?.data && isRecord(settings.data) ? settings.data : {};
  const categoryId = typeof settingsData.dividendIncomeCategoryId === "string"
    ? settingsData.dividendIncomeCategoryId
    : undefined;

  if (!categoryId) {
    return null;
  }

  const category = await prisma.expenseCategory.findUnique({
    where: { id_userId: { id: categoryId, userId } },
  });

  if (!category) {
    return null;
  }

  const subCategoryId = typeof settingsData.dividendIncomeSubCategoryId === "string"
    ? settingsData.dividendIncomeSubCategoryId
    : undefined;
  const subCategories = Array.isArray(category.subCategories)
    ? (category.subCategories as Array<{ id: string; name: string }>)
    : [];
  const subCategory = subCategoryId
    ? subCategories.find((candidate) => candidate.id === subCategoryId)
    : undefined;

  return {
    categoryId,
    categoryName: category.name,
    subCategoryId,
    subCategoryName: subCategory?.name,
  };
}

function mapAssetForScrape(asset: {
  id: string;
  ticker: string;
  name: string;
  type: string;
  quantity: number;
  metadata: Prisma.JsonValue;
  createdAt: Date;
}): LocalAssetForScrape {
  return {
    id: asset.id,
    ticker: asset.ticker,
    name: asset.name,
    type: asset.type as AssetType,
    quantity: asset.quantity,
    metadata: asset.metadata,
    createdAt: asset.createdAt,
  };
}

function isRecord(input: unknown): input is Record<string, unknown> {
  return typeof input === "object" && input !== null && !Array.isArray(input);
}
