import "server-only";

import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/server/prisma";
import type { Dividend, DividendFormData } from "@/types/dividend";

export type LocalDividendListFilters = {
  assetId?: string;
  startDate?: Date;
  endDate?: Date;
};

type AssetRow = {
  id: string;
  ticker: string;
  name: string;
  metadata: Prisma.JsonValue;
};

type DividendRow = {
  id: string;
  userId: string;
  assetId: string;
  assetTicker: string;
  assetName: string;
  assetIsin: string | null;
  exDate: Date;
  paymentDate: Date;
  dividendPerShare: number;
  quantity: number;
  grossAmount: number;
  taxAmount: number;
  netAmount: number;
  currency: string;
  dividendType: string;
  notes: string | null;
  isAutoGenerated: boolean;
  expenseId: string | null;
  grossAmountEur: number | null;
  taxAmountEur: number | null;
  netAmountEur: number | null;
  exchangeRate: number | null;
  costPerShare: number | null;
  createdAt: Date;
  updatedAt: Date;
};

export async function listLocalDividends(
  userId: string,
  filters: LocalDividendListFilters = {}
): Promise<Dividend[]> {
  const rows = await prisma.dividend.findMany({
    where: buildDividendWhere(userId, filters),
    orderBy: [{ paymentDate: "desc" }, { createdAt: "desc" }],
  });

  return rows.map(mapDividendRow);
}

export async function getLocalDividendById(
  userId: string,
  dividendId: string
): Promise<Dividend | null> {
  const row = await prisma.dividend.findFirst({
    where: { id: dividendId, userId },
  });

  return row ? mapDividendRow(row) : null;
}

export async function createLocalDividend(
  userId: string,
  dividendData: DividendFormData
): Promise<Dividend> {
  const asset = await prisma.asset.findUnique({
    where: { id_userId: { id: dividendData.assetId, userId } },
  });

  if (!asset) {
    throw new Error("Asset not found");
  }

  const row = await prisma.dividend.create({
    data: {
      userId,
      ...buildDividendData(dividendData, asset),
    },
  });

  return mapDividendRow(row);
}

export async function updateLocalDividend(
  userId: string,
  dividendId: string,
  updates: Partial<DividendFormData>
): Promise<Dividend | null> {
  try {
    const asset = updates.assetId
      ? await prisma.asset.findUnique({
          where: { id_userId: { id: updates.assetId, userId } },
        })
      : undefined;

    if (updates.assetId && !asset) {
      throw new Error("Asset not found");
    }

    const row = await prisma.dividend.update({
      where: { id_userId: { id: dividendId, userId } },
      data: buildDividendUpdateData(updates, asset),
    });

    return mapDividendRow(row);
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") {
      return null;
    }

    throw error;
  }
}

export async function deleteLocalDividend(
  userId: string,
  dividendId: string
): Promise<boolean> {
  const result = await prisma.dividend.deleteMany({
    where: { id: dividendId, userId },
  });

  return result.count > 0;
}

function buildDividendWhere(
  userId: string,
  filters: LocalDividendListFilters
): Prisma.DividendWhereInput {
  const where: Prisma.DividendWhereInput = { userId };

  if (filters.assetId) {
    where.assetId = filters.assetId;
  }

  if (filters.startDate || filters.endDate) {
    where.paymentDate = {
      gte: filters.startDate,
      lte: filters.endDate,
    };
  }

  return where;
}

function buildDividendData(
  dividendData: DividendFormData,
  asset: AssetRow
): Omit<Prisma.DividendUncheckedCreateInput, "userId"> {
  const metadata = isRecord(asset.metadata) ? asset.metadata : {};

  return {
    assetId: dividendData.assetId,
    assetTicker: asset.ticker,
    assetName: asset.name,
    assetIsin: typeof metadata.isin === "string" ? metadata.isin : undefined,
    exDate: dividendData.exDate,
    paymentDate: dividendData.paymentDate,
    dividendPerShare: dividendData.dividendPerShare,
    quantity: dividendData.quantity,
    grossAmount: dividendData.grossAmount,
    taxAmount: dividendData.taxAmount,
    netAmount: dividendData.netAmount || (dividendData.grossAmount - dividendData.taxAmount),
    currency: dividendData.currency,
    dividendType: dividendData.dividendType,
    notes: dividendData.notes,
    isAutoGenerated: dividendData.isAutoGenerated,
    costPerShare: dividendData.costPerShare ?? getAverageCost(metadata),
  };
}

function buildDividendUpdateData(
  updates: Partial<DividendFormData>,
  asset?: AssetRow | null
): Prisma.DividendUncheckedUpdateInput {
  const netAmount = updates.netAmount ?? (
    updates.grossAmount !== undefined && updates.taxAmount !== undefined
      ? updates.grossAmount - updates.taxAmount
      : undefined
  );
  const metadata = asset && isRecord(asset.metadata) ? asset.metadata : {};

  return stripUndefined({
    assetId: updates.assetId,
    assetTicker: asset?.ticker,
    assetName: asset?.name,
    assetIsin: typeof metadata.isin === "string" ? metadata.isin : undefined,
    exDate: updates.exDate,
    paymentDate: updates.paymentDate,
    dividendPerShare: updates.dividendPerShare,
    quantity: updates.quantity,
    grossAmount: updates.grossAmount,
    taxAmount: updates.taxAmount,
    netAmount,
    currency: updates.currency,
    dividendType: updates.dividendType,
    notes: updates.notes,
    isAutoGenerated: updates.isAutoGenerated,
    costPerShare: updates.costPerShare ?? getAverageCost(metadata),
  });
}

function mapDividendRow(row: DividendRow): Dividend {
  return {
    id: row.id,
    userId: row.userId,
    assetId: row.assetId,
    assetTicker: row.assetTicker,
    assetName: row.assetName,
    assetIsin: row.assetIsin ?? undefined,
    exDate: row.exDate,
    paymentDate: row.paymentDate,
    dividendPerShare: row.dividendPerShare,
    quantity: row.quantity,
    grossAmount: row.grossAmount,
    taxAmount: row.taxAmount,
    netAmount: row.netAmount,
    currency: row.currency,
    dividendType: row.dividendType as Dividend["dividendType"],
    notes: row.notes ?? undefined,
    isAutoGenerated: row.isAutoGenerated,
    expenseId: row.expenseId ?? undefined,
    grossAmountEur: row.grossAmountEur ?? undefined,
    taxAmountEur: row.taxAmountEur ?? undefined,
    netAmountEur: row.netAmountEur ?? undefined,
    exchangeRate: row.exchangeRate ?? undefined,
    costPerShare: row.costPerShare ?? undefined,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function getAverageCost(metadata: Record<string, unknown>): number | undefined {
  return typeof metadata.averageCost === "number" ? metadata.averageCost : undefined;
}

function isRecord(input: unknown): input is Record<string, unknown> {
  return typeof input === "object" && input !== null && !Array.isArray(input);
}

function stripUndefined<T extends Record<string, unknown>>(input: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(input).filter(([, value]) => value !== undefined)
  ) as Partial<T>;
}
