// WARNING: If you add a type here, also update:
// - DividendTable.tsx (type badge map)
// - DividendDetailsDialog.tsx (type labels + badge map)
// - DividendTrackingTab.tsx (type labels)
// - DividendDialog.tsx (select options + Zod enum)
// - dividendService.ts (byType initializer in calculateDividendStats)
export type DividendType = 'ordinary' | 'extraordinary' | 'interim' | 'final' | 'coupon' | 'finalPremium';
// coupon: bond coupon payment, auto-generated from BondDetails on asset save
// finalPremium: one-time bonus paid at maturity (e.g. BTP Valore 0.8%)

// Dividend payment record for a specific asset.
// Supports manual entry and automatic scraping from Borsa Italiana (via ISIN).
// Currency conversion to EUR is automatic for non-EUR dividends using Frankfurter API.
export interface Dividend {
  id: string;
  userId: string;
  assetId: string;
  // WARNING: assetTicker and assetName are denormalized for query performance.
  // When updating an asset's ticker/name, also update all associated dividends via bulk update.
  assetTicker: string; // Denormalized for efficient queries
  assetName: string; // Denormalized for efficient queries
  assetIsin?: string; // Optional ISIN code
  exDate: Date; // Ex-dividend date
  paymentDate: Date; // Payment date
  dividendPerShare: number; // Dividend amount per share
  quantity: number; // Number of shares owned at ex-date
  grossAmount: number; // Total gross dividend (dividendPerShare × quantity)
  taxAmount: number; // Withholding tax amount
  netAmount: number; // Net dividend after tax (grossAmount - taxAmount)
  currency: string; // Currency code (e.g., EUR, USD)
  dividendType: DividendType; // Type of dividend
  notes?: string; // Optional notes
  isAutoGenerated: boolean; // True if created via Borsa Italiana scraping (requires ISIN), false if manually entered
  expenseId?: string; // Reference to corresponding expense entry (if synced)
  // Currency conversion fields (populated automatically if currency !== EUR)
  // Uses Frankfurter API with 24h cache. If conversion fails, these fields remain undefined.
  // Exchange rate format: 1 originalCurrency = X EUR (e.g., 1 USD = 0.92 EUR)
  grossAmountEur?: number; // Gross amount converted to EUR
  taxAmountEur?: number; // Tax amount converted to EUR
  netAmountEur?: number; // Net amount converted to EUR
  exchangeRate?: number; // Exchange rate used for conversion (originalCurrency -> EUR)
  // Historical cost basis snapshot: asset.averageCost (EUR per share) at the time of payment.
  // Used by calculateYocMetrics to compute YOC with the cost basis that was in effect when
  // the dividend was received, rather than the current (potentially different) averageCost.
  // Undefined for legacy records created before this field was introduced — those fall back
  // to the current asset.averageCost.
  costPerShare?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface DividendFormData {
  assetId: string;
  exDate: Date;
  paymentDate: Date;
  dividendPerShare: number;
  quantity: number;
  grossAmount: number;
  taxAmount: number;
  netAmount: number;
  currency: string;
  dividendType: DividendType;
  notes?: string;
  isAutoGenerated: boolean;
  // Server-set snapshot of asset.averageCost at payment time — never from user input.
  costPerShare?: number;
}

export interface DividendStats {
  totalGross: number;
  totalTax: number;
  totalNet: number;
  count: number;
  byAsset: {
    [assetId: string]: {
      assetTicker: string;
      assetName: string;
      totalGross: number;
      totalTax: number;
      totalNet: number;
      count: number;
    };
  };
  byType: {
    [type in DividendType]: {
      totalGross: number;
      totalTax: number;
      totalNet: number;
      count: number;
    };
  };
  // Yield on Cost (YOC) Analysis
  //
  // YOC measures dividend yield based on your original purchase price (average cost),
  // not the current market price. This shows the return on your initial investment.
  //
  // Formula: YOC% = (TTM Gross Dividends / Total Cost Basis) × 100
  //
  // Example:
  // - Bought 100 shares at €50/share (cost basis: €5,000)
  // - Current price: €80/share
  // - TTM dividends: €300
  // - YOC = (€300 / €5,000) × 100 = 6%
  // - Current Yield = (€300 / €8,000) × 100 = 3.75%
  //
  // YOC > Current Yield indicates dividend growth over time.
  portfolioYieldOnCost?: number;
  totalCostBasis?: number;
  yieldOnCostAssets?: YieldOnCostAsset[];
  totalReturnAssets?: TotalReturnAsset[];
}

export interface YieldOnCostAsset {
  assetId: string;
  assetTicker: string;
  assetName: string;
  quantity: number;
  averageCost: number;
  currentPrice: number;
  ttmGrossDividends: number; // TTM (Trailing Twelve Months) gross dividends: sum of last 12 months of dividend payments
  yocPercentage: number;
  currentYieldPercentage: number;
  difference: number;
}

// Per-asset total return combining unrealized capital gain and all-time net dividend income.
// Both components are expressed as % of the original cost basis (quantity × averageCost).
// Only computed for assets with averageCost > 0, quantity > 0, and at least one paid dividend.
export interface TotalReturnAsset {
  assetId: string;
  assetTicker: string;
  assetName: string;
  quantity: number;
  averageCost: number;              // EUR per unit (original purchase cost)
  currentPrice: number;             // EUR per unit (current market price)
  costBasis: number;                // quantity × averageCost
  currentValue: number;             // quantity × currentPrice
  allTimeNetDividends: number;      // All-time net dividends in EUR (netAmountEur ?? netAmount)
  capitalGainAbsolute: number;      // currentValue - costBasis
  capitalGainPercentage: number;    // capitalGainAbsolute / costBasis × 100
  dividendReturnPercentage: number; // allTimeNetDividends / costBasis × 100
  totalReturnPercentage: number;    // capitalGainPercentage + dividendReturnPercentage
}

// DPS (Dividend Per Share) growth analysis — equity only, excludes coupons and finalPremium.
// Tracks the sum of gross dividendPerShare per calendar year, then computes YoY and CAGR.
// Only assets with quantity > 0 and at least 1 year of paid dividends are included.
export interface AssetDividendGrowth {
  assetId: string;
  assetTicker: string;
  assetName: string;
  currency: string;
  // Sum of dividendPerShare for all equity dividends paid in each year, sorted ascending
  yearlyDps: Array<{ year: number; totalDps: number }>;
  // YoY growth % from previous data-year to this year: { 2024: 5.2, 2025: 3.1 }
  yoyGrowth: Record<number, number>;
  // CAGR from first to last data year: (DPSlast/DPSfirst)^(1/(lastYear-firstYear))-1 × 100
  // undefined when only 1 data year exists
  cagr?: number;
  // YoY growth for the most recent year with a predecessor (used for portfolio median)
  latestYoyGrowth?: number;
}

// Portfolio-level DPS growth summary: aggregate across all active equity assets.
export interface DividendGrowthData {
  byAsset: AssetDividendGrowth[];
  // Median of latestYoyGrowth across assets that have >= 2 data years
  portfolioMedianGrowth?: number;
  // Average of latestYoyGrowth across assets that have >= 2 data years
  portfolioAvgGrowth?: number;
}

export interface ScrapedDividend {
  exDate: Date;
  paymentDate: Date;
  dividendPerShare: number;
  currency: string;
  dividendType: DividendType;
}

export interface DividendsByAsset {
  assetId: string;
  assetTicker: string;
  assetName: string;
  dividends: Dividend[];
  totalGross: number;
  totalTax: number;
  totalNet: number;
}
