import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import {
  assertWritableUser,
  AuthSessionError,
  requireUserSession,
} from "@/lib/server/auth/session";
import {
  deleteLocalDividend,
  updateLocalDividend,
} from "@/lib/server/dividends/localDividendService";

const dateFromInputSchema = z.preprocess((value) => {
  if (typeof value === "string" || value instanceof Date) {
    return new Date(value);
  }

  return value;
}, z.date());

const dividendTypeSchema = z.enum([
  "ordinary",
  "extraordinary",
  "interim",
  "final",
  "coupon",
  "finalPremium",
]);

const dividendUpdatesSchema = z.object({
  assetId: z.string().min(1).optional(),
  exDate: dateFromInputSchema.optional(),
  paymentDate: dateFromInputSchema.optional(),
  dividendPerShare: z.number().positive().optional(),
  quantity: z.number().positive().optional(),
  grossAmount: z.number().min(0).optional(),
  taxAmount: z.number().min(0).optional(),
  netAmount: z.number().min(0).optional(),
  currency: z.string().min(1).optional(),
  dividendType: dividendTypeSchema.optional(),
  notes: z.string().optional(),
  isAutoGenerated: z.boolean().optional(),
}).refine((updates) => Object.keys(updates).length > 0, {
  message: "Nessun aggiornamento fornito.",
});

const updateDividendSchema = z.object({
  updates: dividendUpdatesSchema,
});

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ dividendId: string }> }
) {
  try {
    const user = await requireUserSession();
    assertWritableUser(user);

    const { dividendId } = await params;
    const body: unknown = await request.json();
    const parsedBody = updateDividendSchema.safeParse(body);

    if (!parsedBody.success) {
      return NextResponse.json(
        { error: "Aggiornamento dividendo non valido.", issues: parsedBody.error.flatten() },
        { status: 400 }
      );
    }

    const dividend = await updateLocalDividend(
      user.id,
      dividendId,
      parsedBody.data.updates
    );

    if (!dividend) {
      return NextResponse.json(
        { error: "Dividendo non trovato." },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      message: "Dividendo aggiornato con successo",
    });
  } catch (error) {
    return handleDividendItemRouteError(error, "[LOCAL_DIVIDEND_PUT_ERROR]");
  }
}

export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ dividendId: string }> }
) {
  try {
    const user = await requireUserSession();
    assertWritableUser(user);

    const { dividendId } = await params;
    const deleted = await deleteLocalDividend(user.id, dividendId);

    if (!deleted) {
      return NextResponse.json(
        { error: "Dividendo non trovato." },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      message: "Dividendo eliminato con successo",
    });
  } catch (error) {
    return handleDividendItemRouteError(error, "[LOCAL_DIVIDEND_DELETE_ERROR]");
  }
}

function handleDividendItemRouteError(error: unknown, logMessage: string) {
  if (error instanceof AuthSessionError) {
    return NextResponse.json(
      { error: error.message },
      { status: error.code === "UNAUTHENTICATED" ? 401 : 403 }
    );
  }

  if (error instanceof Error && error.message === "Asset not found") {
    return NextResponse.json({ error: "Asset non trovato." }, { status: 404 });
  }

  console.error(logMessage, error);
  return NextResponse.json(
    { error: "Si e verificato un errore durante la gestione dividendi." },
    { status: 500 }
  );
}
