import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import {
  assertWritableUser,
  AuthSessionError,
  requireUserSession,
} from "@/lib/server/auth/session";
import {
  createLocalDividend,
  listLocalDividends,
} from "@/lib/server/dividends/localDividendService";

const dateFromInputSchema = z.preprocess((value) => {
  if (typeof value === "string" || value instanceof Date) {
    return new Date(value);
  }

  return value;
}, z.date());

const dividendTypeSchema = z.enum([
  "ordinary",
  "extraordinary",
  "interim",
  "final",
  "coupon",
  "finalPremium",
]);

const dividendDataSchema = z.object({
  assetId: z.string().min(1),
  exDate: dateFromInputSchema,
  paymentDate: dateFromInputSchema,
  dividendPerShare: z.number().positive(),
  quantity: z.number().positive(),
  grossAmount: z.number().min(0),
  taxAmount: z.number().min(0),
  netAmount: z.number().min(0),
  currency: z.string().min(1),
  dividendType: dividendTypeSchema,
  notes: z.string().optional(),
  isAutoGenerated: z.boolean().default(false),
}).refine((data) => data.paymentDate >= data.exDate, {
  message: "La data di pagamento non puo precedere la data ex-dividend.",
  path: ["paymentDate"],
});

const createDividendSchema = z.object({
  dividendData: dividendDataSchema,
});

export async function GET(request: NextRequest) {
  try {
    const user = await requireUserSession();
    const searchParams = request.nextUrl.searchParams;
    const assetId = searchParams.get("assetId") ?? undefined;
    const startDateValue = searchParams.get("startDate");
    const endDateValue = searchParams.get("endDate");

    const parsedDates = z.object({
      startDate: dateFromInputSchema.optional(),
      endDate: dateFromInputSchema.optional(),
    }).safeParse({
      startDate: startDateValue ?? undefined,
      endDate: endDateValue ?? undefined,
    });

    if (!parsedDates.success) {
      return NextResponse.json(
        { error: "Filtro date non valido.", issues: parsedDates.error.flatten() },
        { status: 400 }
      );
    }

    const dividends = await listLocalDividends(user.id, {
      assetId,
      startDate: parsedDates.data.startDate,
      endDate: parsedDates.data.endDate,
    });

    return NextResponse.json({
      success: true,
      dividends,
      count: dividends.length,
    });
  } catch (error) {
    return handleDividendsRouteError(error, "[LOCAL_DIVIDENDS_GET_ERROR]");
  }
}

export async function POST(request: NextRequest) {
  try {
    const user = await requireUserSession();
    assertWritableUser(user);

    const body: unknown = await request.json();
    const parsedBody = createDividendSchema.safeParse(body);

    if (!parsedBody.success) {
      return NextResponse.json(
        { error: "Dividendo non valido.", issues: parsedBody.error.flatten() },
        { status: 400 }
      );
    }

    const dividend = await createLocalDividend(user.id, parsedBody.data.dividendData);

    return NextResponse.json(
      {
        success: true,
        id: dividend.id,
        message: "Dividendo creato con successo",
      },
      { status: 201 }
    );
  } catch (error) {
    return handleDividendsRouteError(error, "[LOCAL_DIVIDENDS_POST_ERROR]");
  }
}

function handleDividendsRouteError(error: unknown, logMessage: string) {
  if (error instanceof AuthSessionError) {
    return NextResponse.json(
      { error: error.message },
      { status: error.code === "UNAUTHENTICATED" ? 401 : 403 }
    );
  }

  if (error instanceof Error && error.message === "Asset not found") {
    return NextResponse.json({ error: "Asset non trovato." }, { status: 404 });
  }

  console.error(logMessage, error);
  return NextResponse.json(
    { error: "Si e verificato un errore durante la gestione dividendi." },
    { status: 500 }
  );
}
