import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('server-only', () => ({}));
vi.mock('@/lib/firebase/config', () => ({ auth: { currentUser: null }, db: {} }));

const {
  createDividendMock,
  deleteUpcomingCouponsForAssetMock,
  deleteUpcomingFinalPremiumForAssetMock,
  getDividendByIdMock,
  createExpenseFromDividendMock,
  getLocalSettingsMock,
  listLocalExpenseCategoriesMock,
} = vi.hoisted(() => ({
  createDividendMock: vi.fn(),
  deleteUpcomingCouponsForAssetMock: vi.fn(),
  deleteUpcomingFinalPremiumForAssetMock: vi.fn(),
  getDividendByIdMock: vi.fn(),
  createExpenseFromDividendMock: vi.fn(),
  getLocalSettingsMock: vi.fn(),
  listLocalExpenseCategoriesMock: vi.fn(),
}));

vi.mock('@/lib/services/dividendService', () => ({
  createDividend: createDividendMock,
  deleteUpcomingCouponsForAsset: deleteUpcomingCouponsForAssetMock,
  deleteUpcomingFinalPremiumForAsset: deleteUpcomingFinalPremiumForAssetMock,
  getDividendById: getDividendByIdMock,
}));

vi.mock('@/lib/services/dividendIncomeService', () => ({
  createExpenseFromDividend: createExpenseFromDividendMock,
}));

vi.mock('@/lib/server/settings/localSettingsService', () => ({
  getLocalSettings: getLocalSettingsMock,
}));

vi.mock('@/lib/server/cashflow/localExpenseCategoryService', () => ({
  listLocalExpenseCategories: listLocalExpenseCategoriesMock,
}));

import { createDividendWithOptionalExpense } from '@/lib/server/dividendUseCase';
import { DividendFormData } from '@/types/dividend';
import { Asset } from '@/types/assets';

const baseAsset: Asset & { id: string } = {
  id: 'asset-1',
  userId: 'user-1',
  ticker: 'ENI',
  name: 'Eni SpA',
  isin: 'IT0003132476',
  assetClass: 'equity',
  type: 'stock',
  quantity: 100,
  currentPrice: 14.5,
  averageCost: 12,
  currency: 'EUR',
  isLiquid: true,
  includeInHistoryTables: true,
} as any;

function makeFormData(overrides: Partial<DividendFormData> = {}): DividendFormData {
  return {
    assetId: 'asset-1',
    exDate: new Date('2024-01-10'),
    paymentDate: new Date('2024-01-15'),
    dividendPerShare: 0.5,
    quantity: 100,
    grossAmount: 50,
    taxAmount: 13,
    netAmount: 37,
    currency: 'EUR',
    dividendType: 'ordinary',
    isAutoGenerated: false,
    ...overrides,
  };
}

describe('createDividendWithOptionalExpense', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    createDividendMock.mockResolvedValue('div-123');
    getLocalSettingsMock.mockResolvedValue(null);
    listLocalExpenseCategoriesMock.mockResolvedValue([]);
  });

  it('creates dividend and expense when paymentDate is in the past and category is configured', async () => {
    // paymentDate as string (simulates JSON deserialization from client)
    const pastDate = '2020-06-01T00:00:00.000Z' as unknown as Date;
    const formData = makeFormData({ paymentDate: pastDate });

    getLocalSettingsMock.mockResolvedValue({
      targets: {},
      dividendIncomeCategoryId: 'cat-1',
      dividendIncomeSubCategoryId: 'sub-1',
    });
    listLocalExpenseCategoriesMock.mockResolvedValue([{
      id: 'cat-1',
      userId: 'user-1',
      name: 'Dividendi',
      type: 'income',
      subCategories: [{ id: 'sub-1', name: 'Azioni' }],
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    }]);
    getDividendByIdMock.mockResolvedValue({ id: 'div-123', netAmount: 37, currency: 'EUR' });
    createExpenseFromDividendMock.mockResolvedValue('expense-456');

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: 'expense-456' });
    expect(createDividendMock).toHaveBeenCalledOnce();
    expect(getLocalSettingsMock).toHaveBeenCalledWith('user-1');
    expect(listLocalExpenseCategoriesMock).toHaveBeenCalledWith('user-1');
    expect(createExpenseFromDividendMock).toHaveBeenCalledOnce();
  });

  it('creates dividend without expense when paymentDate is in the future', async () => {
    const futureDate = new Date(Date.now() + 1000 * 60 * 60 * 24 * 30); // 30 days ahead
    const formData = makeFormData({ paymentDate: futureDate });

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: undefined });
    expect(createDividendMock).toHaveBeenCalledOnce();
    expect(getLocalSettingsMock).not.toHaveBeenCalled();
    expect(listLocalExpenseCategoriesMock).not.toHaveBeenCalled();
    expect(createExpenseFromDividendMock).not.toHaveBeenCalled();
  });

  it('creates dividend without expense when dividendIncomeCategoryId is not configured', async () => {
    const pastDate = new Date('2020-06-01');
    const formData = makeFormData({ paymentDate: pastDate });

    getLocalSettingsMock.mockResolvedValue({ targets: {} });

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: undefined });
    expect(listLocalExpenseCategoriesMock).not.toHaveBeenCalled();
    expect(createExpenseFromDividendMock).not.toHaveBeenCalled();
  });

  it('returns skipped for auto-generated coupon with quantity 0 (asset sold)', async () => {
    const formData = makeFormData({
      dividendType: 'coupon',
      isAutoGenerated: true,
      quantity: 0,
    });

    deleteUpcomingCouponsForAssetMock.mockResolvedValue(undefined);

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: true, reason: expect.stringContaining('asset sold') });
    expect(deleteUpcomingCouponsForAssetMock).toHaveBeenCalledWith('user-1', 'asset-1');
    expect(createDividendMock).not.toHaveBeenCalled();
  });

  it('returns skipped for auto-generated finalPremium with quantity 0 (asset sold)', async () => {
    const formData = makeFormData({
      dividendType: 'finalPremium',
      isAutoGenerated: true,
      quantity: 0,
    });

    deleteUpcomingFinalPremiumForAssetMock.mockResolvedValue(undefined);

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: true, reason: expect.stringContaining('asset sold') });
    expect(deleteUpcomingFinalPremiumForAssetMock).toHaveBeenCalledWith('user-1', 'asset-1');
    expect(createDividendMock).not.toHaveBeenCalled();
  });

  it('enriches dividend with costPerShare from asset', async () => {
    const futureDate = new Date(Date.now() + 1000 * 60 * 60 * 24 * 30);
    const formData = makeFormData({ paymentDate: futureDate });

    await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    const enrichedData = createDividendMock.mock.calls[0][1];
    expect(enrichedData.costPerShare).toBe(baseAsset.averageCost);
  });

  it('returns dividendId with no expenseId when expense creation fails (non-fatal)', async () => {
    const pastDate = new Date('2020-06-01');
    const formData = makeFormData({ paymentDate: pastDate });

    getLocalSettingsMock.mockResolvedValue({
      targets: {},
      dividendIncomeCategoryId: 'cat-1',
    });
    listLocalExpenseCategoriesMock.mockResolvedValue([{
      id: 'cat-1',
      userId: 'user-1',
      name: 'Dividendi',
      type: 'income',
      subCategories: [],
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    }]);
    getDividendByIdMock.mockResolvedValue({ id: 'div-123' });
    createExpenseFromDividendMock.mockRejectedValue(new Error('Firestore error'));

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    // Dividend created; expense failure is non-fatal
    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: undefined });
  });
});
