import { beforeEach, describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Dividend } from '@/types/dividend';

vi.mock('server-only', () => ({}));

const {
  createLocalExpenseMock,
  updateLocalExpenseMock,
  deleteLocalExpenseMock,
  getLocalExpenseByIdMock,
  updateDividendMock,
  getDividendByIdMock,
  adminCollectionMock,
  adminAddMock,
  adminDocMock,
  adminUpdateMock,
  adminDeleteMock,
  timestampFromDateMock,
  timestampNowMock,
} = vi.hoisted(() => ({
  createLocalExpenseMock: vi.fn(),
  updateLocalExpenseMock: vi.fn(),
  deleteLocalExpenseMock: vi.fn(),
  getLocalExpenseByIdMock: vi.fn(),
  updateDividendMock: vi.fn(),
  getDividendByIdMock: vi.fn(),
  adminCollectionMock: vi.fn(),
  adminAddMock: vi.fn(),
  adminDocMock: vi.fn(),
  adminUpdateMock: vi.fn(),
  adminDeleteMock: vi.fn(),
  timestampFromDateMock: vi.fn((value: Date) => value),
  timestampNowMock: vi.fn(() => new Date('2026-01-10T00:00:00.000Z')),
}));

vi.mock('@/lib/server/cashflow/localExpenseService', () => ({
  createLocalExpense: createLocalExpenseMock,
  updateLocalExpense: updateLocalExpenseMock,
  deleteLocalExpense: deleteLocalExpenseMock,
  getLocalExpenseById: getLocalExpenseByIdMock,
}));

vi.mock('@/lib/services/dividendService', () => ({
  updateDividend: updateDividendMock,
  getDividendById: getDividendByIdMock,
}));

vi.mock('@/lib/firebase/admin', () => ({
  adminDb: {
    collection: adminCollectionMock,
  },
}));

vi.mock('firebase-admin/firestore', () => ({
  Timestamp: {
    fromDate: timestampFromDateMock,
    now: timestampNowMock,
  },
}));

function createDividend(overrides: Partial<Dividend> = {}): Dividend {
  return {
    id: 'div-1',
    userId: 'user-1',
    assetId: 'asset-1',
    assetTicker: 'ENI',
    assetName: 'Eni Spa',
    exDate: new Date('2026-01-05T00:00:00.000Z'),
    paymentDate: new Date('2026-01-15T00:00:00.000Z'),
    dividendPerShare: 1,
    quantity: 100,
    grossAmount: 100,
    taxAmount: 20,
    netAmount: 80,
    currency: 'EUR',
    dividendType: 'ordinary',
    isAutoGenerated: false,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    ...overrides,
  };
}

describe('dividendIncomeService Firebase Admin migration boundary', () => {
  beforeEach(() => {
    vi.clearAllMocks();

    adminCollectionMock.mockReturnValue({
      add: adminAddMock,
      doc: adminDocMock,
    });

    adminAddMock.mockResolvedValue({ id: 'legacy-expense-id' });
    adminDocMock.mockReturnValue({
      update: adminUpdateMock,
      delete: adminDeleteMock,
    });
    adminUpdateMock.mockResolvedValue(undefined);
    adminDeleteMock.mockResolvedValue(undefined);

    createLocalExpenseMock.mockResolvedValue({ id: 'local-expense-id' });
    updateLocalExpenseMock.mockResolvedValue({ id: 'local-expense-id' });
    deleteLocalExpenseMock.mockResolvedValue(true);
    getLocalExpenseByIdMock.mockResolvedValue({
      id: 'expense-1',
      userId: 'user-1',
      type: 'income',
      categoryId: 'cat-dividends',
      categoryName: 'Dividendi',
      subCategoryId: 'sub-dividend-income',
      subCategoryName: 'Cedole',
      amount: 80,
      currency: 'USD',
      date: new Date('2026-01-15T00:00:00.000Z'),
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    });
    updateDividendMock.mockResolvedValue(undefined);
    getDividendByIdMock.mockResolvedValue(createDividend());
  });

  it('keeps dividendIncomeService free of Firebase Admin runtime imports', () => {
    const source = readFileSync(resolve(process.cwd(), 'lib/services/dividendIncomeService.ts'), 'utf8');

    expect(source).not.toMatch(/from ['"]@\/lib\/firebase\/admin['"]/);
    expect(source).not.toMatch(/from ['"]firebase-admin\/firestore['"]/);
  });

  it('delegates expense creation to local helpers, applies EUR conversion, and updates dividend expenseId', async () => {
    const { createExpenseFromDividend } = await import('@/lib/services/dividendIncomeService');

    const dividend = createDividend({
      currency: 'USD',
      netAmount: 80,
      netAmountEur: 74.2,
      notes: 'Cedola trimestrale',
    });

    const createdExpenseId = await createExpenseFromDividend(
      dividend,
      'cat-dividends',
      'Dividendi',
      'sub-dividend-income',
      'Cedole'
    );

    expect(createLocalExpenseMock).toHaveBeenCalledWith(
      'user-1',
      expect.objectContaining({
        type: 'income',
        categoryId: 'cat-dividends',
        categoryName: 'Dividendi',
        subCategoryId: 'sub-dividend-income',
        subCategoryName: 'Cedole',
        amount: 74.2,
        currency: 'EUR',
        date: new Date('2026-01-15T00:00:00.000Z'),
        linkedInvestmentAssetId: 'asset-1',
        linkedInvestmentAssetName: 'Eni Spa',
        notes: expect.stringContaining('convertiti'),
      })
    );
    expect(updateDividendMock).toHaveBeenCalledWith('div-1', expect.objectContaining({
      expenseId: 'local-expense-id',
    }));
    expect(createdExpenseId).toBe('local-expense-id');
    expect(adminCollectionMock).not.toHaveBeenCalled();
  });

  it('delegates expense updates to local helpers instead of adminDb and Timestamp', async () => {
    const { updateExpenseFromDividend } = await import('@/lib/services/dividendIncomeService');

    const dividend = createDividend({
      currency: 'USD',
      netAmount: 80,
      netAmountEur: 74.2,
    });

    await updateExpenseFromDividend(dividend, 'expense-1', 'Dividendi', 'Cedole');

    expect(getLocalExpenseByIdMock).toHaveBeenCalledWith('user-1', 'expense-1');
    expect(updateLocalExpenseMock).toHaveBeenCalledTimes(1);
    expect(adminCollectionMock).not.toHaveBeenCalled();
    expect(timestampFromDateMock).not.toHaveBeenCalled();
    expect(timestampNowMock).not.toHaveBeenCalled();
  });

  it('delegates expense deletion to local helpers and clears dividend expense linkage', async () => {
    const { deleteExpenseForDividend } = await import('@/lib/services/dividendIncomeService');

    await deleteExpenseForDividend('div-1', 'expense-1');

    expect(getDividendByIdMock).toHaveBeenCalledWith('div-1');
    expect(deleteLocalExpenseMock).toHaveBeenCalledWith('user-1', 'expense-1');
    expect(updateDividendMock).toHaveBeenCalledWith('div-1', expect.objectContaining({
      expenseId: undefined,
    }));
    expect(adminCollectionMock).not.toHaveBeenCalled();
  });
});
