import { beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import type { Asset } from "@/types/assets";
import type { DividendFormData } from "@/types/dividend";
import type { ExpenseCategory } from "@/types/expenses";

vi.mock("server-only", () => ({}));
vi.mock("@/lib/firebase/config", () => ({ auth: { currentUser: null }, db: {} }));

const {
  createDividendMock,
  getDividendByIdMock,
  createExpenseFromDividendMock,
  deleteUpcomingCouponsForAssetMock,
  deleteUpcomingFinalPremiumForAssetMock,
  getLocalSettingsMock,
  listLocalExpenseCategoriesMock,
  settingsDocGetMock,
  categoryDocGetMock,
  adminCollectionMock,
} = vi.hoisted(() => {
  const settingsDocGetMock = vi.fn();
  const categoryDocGetMock = vi.fn();
  const adminCollectionMock = vi.fn((name: string) => {
    if (name === "assetAllocationTargets") {
      return { doc: vi.fn(() => ({ get: settingsDocGetMock })) };
    }

    if (name === "expenseCategories") {
      return { doc: vi.fn(() => ({ get: categoryDocGetMock })) };
    }

    throw new Error(`Unexpected collection: ${name}`);
  });

  return {
    createDividendMock: vi.fn(),
    getDividendByIdMock: vi.fn(),
    createExpenseFromDividendMock: vi.fn(),
    deleteUpcomingCouponsForAssetMock: vi.fn(),
    deleteUpcomingFinalPremiumForAssetMock: vi.fn(),
    getLocalSettingsMock: vi.fn(),
    listLocalExpenseCategoriesMock: vi.fn(),
    settingsDocGetMock,
    categoryDocGetMock,
    adminCollectionMock,
  };
});

vi.mock("@/lib/services/dividendService", () => ({
  createDividend: createDividendMock,
  getDividendById: getDividendByIdMock,
  deleteUpcomingCouponsForAsset: deleteUpcomingCouponsForAssetMock,
  deleteUpcomingFinalPremiumForAsset: deleteUpcomingFinalPremiumForAssetMock,
}));

vi.mock("@/lib/services/dividendIncomeService", () => ({
  createExpenseFromDividend: createExpenseFromDividendMock,
}));

vi.mock("@/lib/server/settings/localSettingsService", () => ({
  getLocalSettings: getLocalSettingsMock,
}));

vi.mock("@/lib/server/cashflow/localExpenseCategoryService", () => ({
  listLocalExpenseCategories: listLocalExpenseCategoriesMock,
}));

vi.mock("@/lib/firebase/admin", () => ({
  adminDb: {
    collection: adminCollectionMock,
  },
}));

import { createDividendWithOptionalExpense } from "@/lib/server/dividendUseCase";

const baseAsset: Asset & { id: string } = {
  id: "asset-1",
  userId: "user-1",
  ticker: "ENI",
  name: "Eni SpA",
  isin: "IT0003132476",
  assetClass: "equity",
  type: "stock",
  quantity: 100,
  currentPrice: 14.5,
  averageCost: 12,
  currency: "EUR",
  isLiquid: true,
  includeInHistoryTables: true,
} as any;

function makeFormData(overrides: Partial<DividendFormData> = {}): DividendFormData {
  return {
    assetId: "asset-1",
    exDate: new Date("2024-01-10"),
    paymentDate: new Date("2024-01-15"),
    dividendPerShare: 0.5,
    quantity: 100,
    grossAmount: 50,
    taxAmount: 13,
    netAmount: 37,
    currency: "EUR",
    dividendType: "ordinary",
    isAutoGenerated: false,
    ...overrides,
  };
}

function makeCategory(overrides: Partial<ExpenseCategory> = {}): ExpenseCategory {
  return {
    id: "cat-1",
    userId: "user-1",
    name: "Dividendi",
    type: "income",
    subCategories: [{ id: "sub-1", name: "Cedole" }],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
    ...overrides,
  };
}

describe("dividendUseCase Firebase Admin migration boundary", () => {
  beforeEach(() => {
    vi.clearAllMocks();

    createDividendMock.mockResolvedValue("div-123");
    getDividendByIdMock.mockResolvedValue({ id: "div-123", userId: "user-1" });
    createExpenseFromDividendMock.mockResolvedValue("expense-456");
    getLocalSettingsMock.mockResolvedValue(null);
    listLocalExpenseCategoriesMock.mockResolvedValue([]);

    settingsDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({
        dividendIncomeCategoryId: "cat-legacy",
        dividendIncomeSubCategoryId: "sub-legacy",
      }),
    });
    categoryDocGetMock.mockResolvedValue({
      id: "cat-legacy",
      exists: true,
      data: () => ({
        name: "Legacy Dividendi",
        subCategories: [{ id: "sub-legacy", name: "Legacy Cedole" }],
      }),
    });
  });

  it("keeps dividendUseCase free of Firebase Admin imports and adminDb symbols", () => {
    const source = readFileSync(resolve(process.cwd(), "lib/server/dividendUseCase.ts"), "utf8");

    expect(source).not.toMatch(/from ['"]@\/lib\/firebase\/admin['"]/);
    expect(source).not.toMatch(/\badminDb\b/);
  });

  it("creates dividend and paid-date expense using local settings and local categories", async () => {
    const pastDate = "2020-06-01T00:00:00.000Z" as unknown as Date;
    const formData = makeFormData({ paymentDate: pastDate });

    getLocalSettingsMock.mockResolvedValue({
      targets: {},
      dividendIncomeCategoryId: "cat-1",
      dividendIncomeSubCategoryId: "sub-1",
    });
    listLocalExpenseCategoriesMock.mockResolvedValue([makeCategory()]);
    getDividendByIdMock.mockResolvedValue({
      id: "div-123",
      userId: "user-1",
      netAmount: 37,
      currency: "EUR",
    });
    settingsDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({
        dividendIncomeCategoryId: "cat-1",
        dividendIncomeSubCategoryId: "sub-1",
      }),
    });
    categoryDocGetMock.mockResolvedValue({
      id: "cat-1",
      exists: true,
      data: () => ({
        name: "Dividendi",
        subCategories: [{ id: "sub-1", name: "Cedole" }],
      }),
    });

    const result = await createDividendWithOptionalExpense("user-1", formData, baseAsset);

    expect(result).toEqual({
      skipped: false,
      dividendId: "div-123",
      expenseId: "expense-456",
    });
    expect(createDividendMock).toHaveBeenCalledOnce();
    expect(getLocalSettingsMock).toHaveBeenCalledWith("user-1");
    expect(listLocalExpenseCategoriesMock).toHaveBeenCalledWith("user-1");
    expect(createExpenseFromDividendMock).toHaveBeenCalledWith(
      expect.objectContaining({ id: "div-123" }),
      "cat-1",
      "Dividendi",
      "sub-1",
      "Cedole"
    );
    expect(adminCollectionMock).not.toHaveBeenCalled();
  });

  it("creates dividend without expense for future payment dates", async () => {
    const futureDate = new Date(Date.now() + 1000 * 60 * 60 * 24 * 30);
    const formData = makeFormData({ paymentDate: futureDate });

    const result = await createDividendWithOptionalExpense("user-1", formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: "div-123", expenseId: undefined });
    expect(createDividendMock).toHaveBeenCalledOnce();
    expect(getLocalSettingsMock).not.toHaveBeenCalled();
    expect(listLocalExpenseCategoriesMock).not.toHaveBeenCalled();
    expect(createExpenseFromDividendMock).not.toHaveBeenCalled();
    expect(adminCollectionMock).not.toHaveBeenCalled();
  });

  it("creates dividend without expense when dividendIncomeCategoryId is missing in local settings", async () => {
    const pastDate = new Date("2020-06-01T00:00:00.000Z");
    const formData = makeFormData({ paymentDate: pastDate });

    getLocalSettingsMock.mockResolvedValue({ targets: {} });
    settingsDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({}),
    });

    const result = await createDividendWithOptionalExpense("user-1", formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: "div-123", expenseId: undefined });
    expect(getLocalSettingsMock).toHaveBeenCalledWith("user-1");
    expect(listLocalExpenseCategoriesMock).not.toHaveBeenCalled();
    expect(createExpenseFromDividendMock).not.toHaveBeenCalled();
    expect(adminCollectionMock).not.toHaveBeenCalled();
  });

  it("keeps expense creation non-fatal when expense service fails", async () => {
    const pastDate = new Date("2020-06-01T00:00:00.000Z");
    const formData = makeFormData({ paymentDate: pastDate });
    const consoleSpy = vi.spyOn(console, "error").mockImplementation(() => {});

    getLocalSettingsMock.mockResolvedValue({
      targets: {},
      dividendIncomeCategoryId: "cat-1",
      dividendIncomeSubCategoryId: "sub-1",
    });
    listLocalExpenseCategoriesMock.mockResolvedValue([makeCategory()]);
    settingsDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({
        dividendIncomeCategoryId: "cat-1",
        dividendIncomeSubCategoryId: "sub-1",
      }),
    });
    categoryDocGetMock.mockResolvedValue({
      id: "cat-1",
      exists: true,
      data: () => ({
        name: "Dividendi",
        subCategories: [{ id: "sub-1", name: "Cedole" }],
      }),
    });
    createExpenseFromDividendMock.mockRejectedValue(new Error("Expense write failed"));

    const result = await createDividendWithOptionalExpense("user-1", formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: "div-123", expenseId: undefined });
    expect(getLocalSettingsMock).toHaveBeenCalledWith("user-1");
    expect(listLocalExpenseCategoriesMock).toHaveBeenCalledWith("user-1");
    expect(createExpenseFromDividendMock).toHaveBeenCalledOnce();
    expect(adminCollectionMock).not.toHaveBeenCalled();

    consoleSpy.mockRestore();
  });
});
