import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

const { prismaMock } = vi.hoisted(() => ({
  prismaMock: {
    asset: {
      findMany: vi.fn(),
    },
    dividend: {
      findMany: vi.fn(),
    },
    investmentOperation: {
      findMany: vi.fn(),
    },
  },
}));

vi.mock("@/lib/server/prisma", () => ({
  prisma: prismaMock,
}));

import { getLocalDividendStats } from "@/lib/server/dividends/localDividendStatsService";

const baseDividend = {
  id: "dividend-1",
  userId: "user-1",
  assetId: "asset-1",
  assetTicker: "ENI",
  assetName: "Eni",
  assetIsin: "IT0003132476",
  exDate: new Date("2026-05-10T00:00:00.000Z"),
  paymentDate: new Date("2026-05-17T00:00:00.000Z"),
  dividendPerShare: 0.5,
  quantity: 100,
  grossAmount: 50,
  taxAmount: 13,
  netAmount: 37,
  currency: "EUR",
  dividendType: "ordinary",
  notes: null,
  isAutoGenerated: false,
  expenseId: null,
  grossAmountEur: null,
  taxAmountEur: null,
  netAmountEur: null,
  exchangeRate: null,
  costPerShare: 14.5,
  legacyFirebaseId: null,
  createdAt: new Date("2026-05-17T10:00:00.000Z"),
  updatedAt: new Date("2026-05-17T10:00:00.000Z"),
};

describe("local dividend stats service", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    prismaMock.asset.findMany.mockResolvedValue([
      {
        id: "asset-1",
        ticker: "ENI",
        name: "Eni",
        quantity: 100,
        currentPrice: 15,
        metadata: { averageCost: 14.5 },
      },
      {
        id: "asset-2",
        ticker: "OLD",
        name: "Sold",
        quantity: 0,
        currentPrice: 10,
        metadata: { averageCost: 8 },
      },
    ]);
    prismaMock.investmentOperation.findMany.mockResolvedValue([]);
  });

  it("calculates paid dividend stats, charts, and active upcoming totals for a user", async () => {
    prismaMock.dividend.findMany.mockResolvedValue([
      baseDividend,
      {
        ...baseDividend,
        id: "dividend-2",
        paymentDate: new Date("2026-06-17T00:00:00.000Z"),
        grossAmount: 40,
        taxAmount: 10,
        netAmount: 30,
        dividendPerShare: 0.4,
      },
      {
        ...baseDividend,
        id: "future-active",
        paymentDate: new Date("2026-08-01T00:00:00.000Z"),
        grossAmount: 20,
        taxAmount: 5,
        netAmount: 15,
      },
      {
        ...baseDividend,
        id: "future-sold",
        assetId: "asset-2",
        assetTicker: "OLD",
        assetName: "Sold",
        paymentDate: new Date("2026-08-01T00:00:00.000Z"),
        grossAmount: 100,
        taxAmount: 26,
        netAmount: 74,
      },
    ]);

    const result = await getLocalDividendStats("user-1", {
      today: new Date("2026-07-01T00:00:00.000Z"),
    });

    expect(prismaMock.dividend.findMany).toHaveBeenCalledWith({
      where: { userId: "user-1" },
      orderBy: [{ paymentDate: "desc" }, { createdAt: "desc" }],
    });
    expect(result.stats.period).toEqual({
      totalGross: 90,
      totalTax: 23,
      totalNet: 67,
      count: 2,
    });
    expect(result.stats.upcomingTotal).toBe(15);
    expect(result.stats.byAsset).toEqual([
      {
        assetTicker: "ENI",
        assetName: "Eni",
        totalNet: 67,
        count: 2,
      },
    ]);
    expect(result.stats.byYear).toEqual([
      { year: 2026, totalGross: 90, totalTax: 23, totalNet: 67 },
    ]);
    expect(result.stats.byMonth).toEqual([
      { month: "2026-05", totalNet: 37 },
      { month: "2026-06", totalNet: 30 },
    ]);
  });

  it("scopes period stats and realized investment summary by selected asset", async () => {
    prismaMock.dividend.findMany.mockResolvedValue([
      baseDividend,
      {
        ...baseDividend,
        id: "other-asset",
        assetId: "asset-2",
        assetTicker: "OLD",
        assetName: "Sold",
        paymentDate: new Date("2026-05-17T00:00:00.000Z"),
        grossAmount: 100,
        taxAmount: 26,
        netAmount: 74,
      },
    ]);
    prismaMock.investmentOperation.findMany.mockResolvedValue([
      {
        assetId: "asset-1",
        assetName: "Eni",
        assetTicker: "ENI",
        type: "sell",
        realizedGain: 25,
        realizedGainTax: 6.5,
        taxes: 0,
      },
      {
        assetId: "asset-2",
        assetName: "Sold",
        assetTicker: "OLD",
        type: "sell",
        realizedGain: 100,
        realizedGainTax: 26,
        taxes: 0,
      },
    ]);

    const result = await getLocalDividendStats("user-1", {
      assetId: "asset-1",
      startDate: new Date("2026-01-01T00:00:00.000Z"),
      endDate: new Date("2026-12-31T23:59:59.999Z"),
      today: new Date("2026-07-01T00:00:00.000Z"),
    });

    expect(result.stats.period.totalNet).toBe(37);
    expect(result.stats.realizedInvestmentSummary).toEqual({
      totalRealizedGain: 25,
      totalRealizedTaxes: 6.5,
      totalNetRealizedGain: 18.5,
      sellsCount: 1,
      byAsset: [
        {
          assetId: "asset-1",
          assetName: "Eni",
          assetTicker: "ENI",
          realizedGain: 25,
          realizedTaxes: 6.5,
          netRealizedGain: 18.5,
          sellsCount: 1,
        },
      ],
    });
  });
});
