import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

const { prismaMock } = vi.hoisted(() => ({
  prismaMock: {
    asset: {
      findUnique: vi.fn(),
    },
    dividend: {
      create: vi.fn(),
      deleteMany: vi.fn(),
      findFirst: vi.fn(),
      findMany: vi.fn(),
      update: vi.fn(),
    },
  },
}));

vi.mock("@/lib/server/prisma", () => ({
  prisma: prismaMock,
}));

import {
  createLocalDividend,
  deleteLocalDividend,
  getLocalDividendById,
  listLocalDividends,
  updateLocalDividend,
} from "@/lib/server/dividends/localDividendService";

const assetRow = {
  id: "asset-1",
  userId: "user-1",
  ticker: "ENI",
  name: "Eni",
  assetClass: "equity",
  currency: "EUR",
  metadata: { isin: "IT0003132476", averageCost: 14.5 },
};

const dividendRow = {
  id: "dividend-1",
  userId: "user-1",
  assetId: "asset-1",
  assetTicker: "ENI",
  assetName: "Eni",
  assetIsin: "IT0003132476",
  exDate: new Date("2026-05-10T00:00:00.000Z"),
  paymentDate: new Date("2026-05-17T00:00:00.000Z"),
  dividendPerShare: 0.5,
  quantity: 100,
  grossAmount: 50,
  taxAmount: 13,
  netAmount: 37,
  currency: "EUR",
  dividendType: "ordinary",
  notes: null,
  isAutoGenerated: false,
  expenseId: null,
  grossAmountEur: null,
  taxAmountEur: null,
  netAmountEur: null,
  exchangeRate: null,
  costPerShare: 14.5,
  legacyFirebaseId: null,
  createdAt: new Date("2026-05-17T10:00:00.000Z"),
  updatedAt: new Date("2026-05-17T10:00:00.000Z"),
};

describe("local dividend service", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("lists dividends scoped to a user ordered by payment date descending", async () => {
    prismaMock.dividend.findMany.mockResolvedValue([dividendRow]);

    const dividends = await listLocalDividends("user-1");

    expect(prismaMock.dividend.findMany).toHaveBeenCalledWith({
      where: { userId: "user-1" },
      orderBy: [{ paymentDate: "desc" }, { createdAt: "desc" }],
    });
    expect(dividends[0]).toMatchObject({
      id: "dividend-1",
      assetTicker: "ENI",
      grossAmount: 50,
      netAmount: 37,
    });
  });

  it("lists dividends with asset and payment date filters", async () => {
    prismaMock.dividend.findMany.mockResolvedValue([]);

    await listLocalDividends("user-1", {
      assetId: "asset-1",
      startDate: new Date("2026-01-01T00:00:00.000Z"),
      endDate: new Date("2026-12-31T23:59:59.999Z"),
    });

    expect(prismaMock.dividend.findMany).toHaveBeenCalledWith({
      where: {
        userId: "user-1",
        assetId: "asset-1",
        paymentDate: {
          gte: new Date("2026-01-01T00:00:00.000Z"),
          lte: new Date("2026-12-31T23:59:59.999Z"),
        },
      },
      orderBy: [{ paymentDate: "desc" }, { createdAt: "desc" }],
    });
  });

  it("creates dividends using user-owned asset metadata", async () => {
    prismaMock.asset.findUnique.mockResolvedValue(assetRow);
    prismaMock.dividend.create.mockResolvedValue(dividendRow);

    const dividend = await createLocalDividend("user-1", {
      assetId: "asset-1",
      exDate: new Date("2026-05-10T00:00:00.000Z"),
      paymentDate: new Date("2026-05-17T00:00:00.000Z"),
      dividendPerShare: 0.5,
      quantity: 100,
      grossAmount: 50,
      taxAmount: 13,
      netAmount: 37,
      currency: "EUR",
      dividendType: "ordinary",
      isAutoGenerated: false,
    });

    expect(prismaMock.asset.findUnique).toHaveBeenCalledWith({
      where: { id_userId: { id: "asset-1", userId: "user-1" } },
    });
    expect(prismaMock.dividend.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        userId: "user-1",
        assetId: "asset-1",
        assetTicker: "ENI",
        assetName: "Eni",
        assetIsin: "IT0003132476",
        grossAmount: 50,
        taxAmount: 13,
        netAmount: 37,
        costPerShare: 14.5,
      }),
    });
    expect(dividend.id).toBe("dividend-1");
  });

  it("returns null when fetching a dividend owned by another user", async () => {
    prismaMock.dividend.findFirst.mockResolvedValue(null);

    await expect(getLocalDividendById("user-1", "dividend-1")).resolves.toBeNull();
    expect(prismaMock.dividend.findFirst).toHaveBeenCalledWith({
      where: { id: "dividend-1", userId: "user-1" },
    });
  });

  it("updates dividends only when they belong to the user", async () => {
    prismaMock.dividend.update.mockResolvedValue({
      ...dividendRow,
      notes: "Aggiornato",
    });

    const dividend = await updateLocalDividend("user-1", "dividend-1", {
      notes: "Aggiornato",
    });

    expect(prismaMock.dividend.update).toHaveBeenCalledWith({
      where: { id_userId: { id: "dividend-1", userId: "user-1" } },
      data: expect.objectContaining({
        notes: "Aggiornato",
      }),
    });
    expect(dividend?.notes).toBe("Aggiornato");
  });

  it("deletes dividends only when they belong to the user", async () => {
    prismaMock.dividend.deleteMany.mockResolvedValue({ count: 1 });

    await expect(deleteLocalDividend("user-1", "dividend-1")).resolves.toBe(true);
    expect(prismaMock.dividend.deleteMany).toHaveBeenCalledWith({
      where: { id: "dividend-1", userId: "user-1" },
    });
  });
});
