import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { UserRole } from "@prisma/client";

vi.mock("server-only", () => ({}));

const {
  assertWritableUserMock,
  createLocalDividendMock,
  deleteLocalDividendMock,
  listLocalDividendsMock,
  requireUserSessionMock,
  updateLocalDividendMock,
} = vi.hoisted(() => ({
  assertWritableUserMock: vi.fn(),
  createLocalDividendMock: vi.fn(),
  deleteLocalDividendMock: vi.fn(),
  listLocalDividendsMock: vi.fn(),
  requireUserSessionMock: vi.fn(),
  updateLocalDividendMock: vi.fn(),
}));

vi.mock("@/lib/server/auth/session", () => ({
  AuthSessionError: class AuthSessionError extends Error {
    constructor(
      message: string,
      public readonly code: string
    ) {
      super(message);
      this.name = "AuthSessionError";
    }
  },
  assertWritableUser: assertWritableUserMock,
  requireUserSession: requireUserSessionMock,
}));

vi.mock("@/lib/server/dividends/localDividendService", () => ({
  createLocalDividend: createLocalDividendMock,
  deleteLocalDividend: deleteLocalDividendMock,
  listLocalDividends: listLocalDividendsMock,
  updateLocalDividend: updateLocalDividendMock,
}));

import {
  GET,
  POST,
} from "@/app/api/dividends/route";
import {
  DELETE,
  PUT,
} from "@/app/api/dividends/[dividendId]/route";
import { AuthSessionError } from "@/lib/server/auth/session";

const authenticatedUser = {
  id: "user-1",
  email: "test@example.com",
  name: "Test User",
  role: UserRole.USER,
  isDemo: false,
};

function createJsonRequest(body: unknown, method = "POST"): NextRequest {
  return new NextRequest("http://localhost/api/dividends", {
    method,
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
}

const routeContext = {
  params: Promise.resolve({ dividendId: "dividend-1" }),
};

describe("local dividends routes", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    requireUserSessionMock.mockResolvedValue(authenticatedUser);
  });

  it("returns dividends for the authenticated user with the existing response shape", async () => {
    listLocalDividendsMock.mockResolvedValue([{ id: "dividend-1" }]);

    const response = await GET(
      new NextRequest("http://localhost/api/dividends?assetId=asset-1")
    );

    expect(response.status).toBe(200);
    expect(listLocalDividendsMock).toHaveBeenCalledWith("user-1", {
      assetId: "asset-1",
      startDate: undefined,
      endDate: undefined,
    });
    await expect(response.json()).resolves.toEqual({
      success: true,
      dividends: [{ id: "dividend-1" }],
      count: 1,
    });
  });

  it("returns 401 without a session", async () => {
    requireUserSessionMock.mockRejectedValue(
      new AuthSessionError("Autenticazione richiesta.", "UNAUTHENTICATED")
    );

    const response = await GET(new NextRequest("http://localhost/api/dividends"));

    expect(response.status).toBe(401);
  });

  it("creates dividends for writable users from the legacy wrapped payload", async () => {
    createLocalDividendMock.mockResolvedValue({ id: "dividend-1" });

    const response = await POST(
      createJsonRequest({
        userId: "legacy-client-user-id",
        dividendData: {
          assetId: "asset-1",
          exDate: "2026-05-10T00:00:00.000Z",
          paymentDate: "2026-05-17T00:00:00.000Z",
          dividendPerShare: 0.5,
          quantity: 100,
          grossAmount: 50,
          taxAmount: 13,
          netAmount: 37,
          currency: "EUR",
          dividendType: "ordinary",
          isAutoGenerated: false,
        },
      })
    );

    expect(response.status).toBe(201);
    expect(assertWritableUserMock).toHaveBeenCalledWith(authenticatedUser);
    expect(createLocalDividendMock).toHaveBeenCalledWith(
      "user-1",
      expect.objectContaining({
        assetId: "asset-1",
        paymentDate: new Date("2026-05-17T00:00:00.000Z"),
      })
    );
    await expect(response.json()).resolves.toEqual({
      success: true,
      id: "dividend-1",
      message: "Dividendo creato con successo",
    });
  });

  it("rejects invalid dividend payloads", async () => {
    const response = await POST(
      createJsonRequest({
        dividendData: {
          assetId: "asset-1",
          exDate: "2026-05-17T00:00:00.000Z",
          paymentDate: "2026-05-10T00:00:00.000Z",
          dividendPerShare: 0,
          quantity: 100,
          grossAmount: 50,
          taxAmount: 13,
          netAmount: 37,
          currency: "EUR",
          dividendType: "ordinary",
          isAutoGenerated: false,
        },
      })
    );

    expect(response.status).toBe(400);
    expect(createLocalDividendMock).not.toHaveBeenCalled();
  });

  it("updates dividends for writable users", async () => {
    updateLocalDividendMock.mockResolvedValue({ id: "dividend-1" });

    const response = await PUT(
      createJsonRequest(
        {
          updates: {
            notes: "Aggiornato",
          },
        },
        "PUT"
      ),
      routeContext
    );

    expect(response.status).toBe(200);
    expect(updateLocalDividendMock).toHaveBeenCalledWith(
      "user-1",
      "dividend-1",
      { notes: "Aggiornato" }
    );
  });

  it("returns 404 when an update target does not exist", async () => {
    updateLocalDividendMock.mockResolvedValue(null);

    const response = await PUT(
      createJsonRequest({ updates: { notes: "Aggiornato" } }, "PUT"),
      routeContext
    );

    expect(response.status).toBe(404);
  });

  it("deletes dividends for writable users", async () => {
    deleteLocalDividendMock.mockResolvedValue(true);

    const response = await DELETE(new NextRequest("http://localhost"), routeContext);

    expect(response.status).toBe(200);
    expect(deleteLocalDividendMock).toHaveBeenCalledWith("user-1", "dividend-1");
  });
});
