import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

const {
  prismaMock,
  scrapeDividendsByIsinMock,
  syncLocalDividendExpensesMock,
} = vi.hoisted(() => ({
  prismaMock: {
    asset: {
      findUnique: vi.fn(),
    },
    dividend: {
      create: vi.fn(),
      findFirst: vi.fn(),
    },
    expenseCategory: {
      findUnique: vi.fn(),
    },
    userSetting: {
      findUnique: vi.fn(),
    },
  },
  scrapeDividendsByIsinMock: vi.fn(),
  syncLocalDividendExpensesMock: vi.fn(),
}));

vi.mock("@/lib/server/prisma", () => ({
  prisma: prismaMock,
}));

vi.mock("@/lib/services/borsaItalianaScraperService", () => ({
  scrapeDividendsByIsin: scrapeDividendsByIsinMock,
}));

vi.mock("@/lib/server/dividends/localDividendExpenseSyncService", () => ({
  syncLocalDividendExpenses: syncLocalDividendExpensesMock,
}));

import { scrapeLocalAssetDividends } from "@/lib/server/dividends/localDividendScrapeService";

const assetRow = {
  id: "asset-1",
  userId: "user-1",
  ticker: "ENI",
  name: "Eni",
  type: "stock",
  quantity: 100,
  metadata: {
    isin: "IT0003132476",
    averageCost: 14.5,
  },
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
};

describe("local dividend scrape service", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    prismaMock.asset.findUnique.mockResolvedValue(assetRow);
    prismaMock.dividend.findFirst.mockResolvedValue(null);
    prismaMock.dividend.create.mockResolvedValue({ id: "dividend-1" });
    prismaMock.expenseCategory.findUnique.mockResolvedValue(null);
    prismaMock.userSetting.findUnique.mockResolvedValue(null);
    syncLocalDividendExpensesMock.mockResolvedValue({ created: 0, skipped: 0, failed: 0 });
  });

  it("scrapes relevant dividends, skips duplicates, and creates local dividend rows", async () => {
    scrapeDividendsByIsinMock.mockResolvedValue([
      {
        exDate: new Date("2025-12-15T00:00:00.000Z"),
        paymentDate: new Date("2026-01-10T00:00:00.000Z"),
        dividendPerShare: 0.4,
        currency: "EUR",
        dividendType: "ordinary",
      },
      {
        exDate: new Date("2026-05-10T00:00:00.000Z"),
        paymentDate: new Date("2026-05-17T00:00:00.000Z"),
        dividendPerShare: 0.5,
        currency: "EUR",
        dividendType: "ordinary",
      },
      {
        exDate: new Date("2026-06-10T00:00:00.000Z"),
        paymentDate: new Date("2026-06-17T00:00:00.000Z"),
        dividendPerShare: 0.25,
        currency: "EUR",
        dividendType: "interim",
      },
    ]);
    prismaMock.dividend.findFirst
      .mockResolvedValueOnce(null)
      .mockResolvedValueOnce({ id: "existing-dividend" });

    const result = await scrapeLocalAssetDividends("user-1", "asset-1", {
      today: new Date("2026-07-01T00:00:00.000Z"),
    });

    expect(prismaMock.asset.findUnique).toHaveBeenCalledWith({
      where: { id_userId: { id: "asset-1", userId: "user-1" } },
    });
    expect(scrapeDividendsByIsinMock).toHaveBeenCalledWith("IT0003132476", "stock");
    expect(prismaMock.dividend.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        userId: "user-1",
        assetId: "asset-1",
        assetTicker: "ENI",
        assetName: "Eni",
        assetIsin: "IT0003132476",
        grossAmount: 50,
        taxAmount: 13,
        netAmount: 37,
        isAutoGenerated: true,
        costPerShare: 14.5,
      }),
    });
    expect(result).toEqual({
      success: true,
      message: "Dividendi importati per ENI",
      scraped: 3,
      filtered: 1,
      created: 1,
      skipped: 1,
      createdIds: ["dividend-1"],
    });
  });

  it("syncs paid imported dividends to local expenses when dividend income settings are configured", async () => {
    scrapeDividendsByIsinMock.mockResolvedValue([
      {
        exDate: new Date("2026-05-10T00:00:00.000Z"),
        paymentDate: new Date("2026-05-17T00:00:00.000Z"),
        dividendPerShare: 0.5,
        currency: "EUR",
        dividendType: "ordinary",
      },
    ]);
    prismaMock.userSetting.findUnique.mockResolvedValue({
      data: {
        dividendIncomeCategoryId: "category-1",
        dividendIncomeSubCategoryId: "subcategory-1",
      },
    });
    prismaMock.expenseCategory.findUnique.mockResolvedValue({
      id: "category-1",
      name: "Dividendi",
      subCategories: [{ id: "subcategory-1", name: "Azioni" }],
    });

    await scrapeLocalAssetDividends("user-1", "asset-1", {
      today: new Date("2026-07-01T00:00:00.000Z"),
    });

    expect(syncLocalDividendExpensesMock).toHaveBeenCalledWith("user-1", {
      dividendIds: ["dividend-1"],
      categoryId: "category-1",
      categoryName: "Dividendi",
      subCategoryId: "subcategory-1",
      subCategoryName: "Azioni",
      today: new Date("2026-07-01T00:00:00.000Z"),
    });
  });

  it("rejects assets without ISIN before calling the scraper", async () => {
    prismaMock.asset.findUnique.mockResolvedValue({
      ...assetRow,
      metadata: {},
    });

    await expect(
      scrapeLocalAssetDividends("user-1", "asset-1")
    ).rejects.toThrow("ASSET_MISSING_ISIN");
    expect(scrapeDividendsByIsinMock).not.toHaveBeenCalled();
  });
});
