/**
 * Guard tests for manual overrides applied to components/ui/sidebar.tsx after
 * every shadcn upgrade.
 *
 * shadcn primitives are regenerated by `npx shadcn@latest add sidebar`, which
 * silently reverts project-specific customisations. These tests read the actual
 * source file so they fail immediately after a shadcn overwrite — no local copy
 * to forget to update.
 *
 * When a test fails here after a shadcn upgrade:
 *   1. Re-apply the override documented in the test.
 *   2. Verify the test passes again before committing.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';

// Read the actual primitive source — this is intentional. We are testing file
// content, not runtime behaviour. Importing the module would require jsdom +
// mocking next/navigation; reading the source is simpler and equally reliable
// for detecting text-level regressions introduced by shadcn upgrades.
const sidebarSource = readFileSync(
  resolve(__dirname, '../components/ui/sidebar.tsx'),
  'utf-8'
);

// ---------------------------------------------------------------------------
// sidebarMenuButtonVariants — active state font weight
// ---------------------------------------------------------------------------
// Override: data-[active=true]:font-semibold
// shadcn default: data-[active=true]:font-medium
//
// Rationale: at text-sm (14px), font-medium is almost imperceptible compared
// to the surrounding font-normal items. font-semibold gives a legible
// typographic signal that reinforces the animated active pill.
// ---------------------------------------------------------------------------

describe('sidebar.tsx — shadcn override: sidebarMenuButtonVariants', () => {
  it('active state uses font-semibold, not the shadcn default font-medium', () => {
    expect(sidebarSource).toContain('data-[active=true]:font-semibold');
  });

  it('does not retain the shadcn default data-[active=true]:font-medium', () => {
    // Presence of font-medium on the active modifier means the override was lost.
    expect(sidebarSource).not.toContain('data-[active=true]:font-medium');
  });
});

// ---------------------------------------------------------------------------
// Sidebar (desktop) — custom breakpoint
// ---------------------------------------------------------------------------
// Override: desktop:block / desktop:flex instead of shadcn defaults md:block / md:flex
//
// Rationale: the project uses --breakpoint-desktop: 1440px (app/globals.css).
// shadcn defaults to md: (768px), which would show the sidebar on tablets and
// landscape mobile — both served by BottomNavigation and the offcanvas Sheet.
// ---------------------------------------------------------------------------

describe('sidebar.tsx — shadcn override: desktop breakpoint', () => {
  it('desktop sidebar wrapper uses desktop:block, not the shadcn default md:block', () => {
    expect(sidebarSource).toContain('desktop:block');
    expect(sidebarSource).not.toMatch(/(?<!"[^"]*)\bmd:block\b(?![^"]*")/);
  });

  it('desktop sidebar container uses desktop:flex, not the shadcn default md:flex', () => {
    expect(sidebarSource).toContain('desktop:flex');
  });
});
